import {
  IsString,
  IsOptional,
  IsArray,
  IsEnum,
  IsNumber,
  IsObject,
  Min,
  Max,
} from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

export class ContentOptimizationDto {
  @ApiProperty({ description: 'Overall optimization score (0-100)' })
  score: number;

  @ApiProperty({ description: 'Letter grade' })
  grade: string;

  @ApiProperty({ description: 'Word count' })
  wordCount: number;

  @ApiProperty({ description: 'Readability analysis' })
  readability: {
    score: number;
    grade: string;
    avgSentenceLength: number;
  };

  @ApiProperty({ description: 'Keyword analysis' })
  keywords: Array<{
    keyword: string;
    count: number;
    density: number;
    isOptimal: boolean;
    inTitle: boolean;
    inFirstParagraph: boolean;
    suggestions: string[];
  }>;

  @ApiProperty({ description: 'Content structure analysis' })
  structure: {
    hasHeaders: boolean;
    hasLists: boolean;
    hasLinks: boolean;
    hasImages: boolean;
    paragraphCount: number;
  };

  @ApiProperty({ description: 'Optimization suggestions', type: [String] })
  suggestions: string[];

  @ApiProperty({ description: 'Opportunities for improvement', type: [String] })
  opportunities: string[];

  @ApiProperty({ description: 'Warnings', type: [String] })
  warnings: string[];

  @ApiProperty({ description: 'Estimated impact of fixes' })
  estimatedImpact: string;
}

export class KeywordSuggestionDto {
  @ApiProperty({ description: 'Suggested keyword' })
  keyword: string;

  @ApiProperty({ description: 'Monthly search volume' })
  searchVolume: number;

  @ApiProperty({ description: 'Keyword difficulty (0-100)' })
  difficulty: number;

  @ApiProperty({ description: 'Cost per click' })
  cpc: number;

  @ApiProperty({ description: 'Search intent' })
  intent: SearchIntentDto;

  @ApiProperty({ description: 'Trend direction' })
  trend: 'rising' | 'stable' | 'declining';

  @ApiProperty({ description: 'Related keywords', type: [String] })
  relatedKeywords: string[];

  @ApiProperty({ description: 'SERP features' })
  serp: {
    hasFeatureSnippet: boolean;
    hasPeopleAlsoAsk: boolean;
    hasLocalPack: boolean;
    hasImages: boolean;
    hasVideos: boolean;
  };
}

export class SearchIntentDto {
  @ApiProperty({ description: 'Intent type' })
  type: 'informational' | 'navigational' | 'transactional' | 'commercial';

  @ApiProperty({ description: 'Confidence score (0-1)' })
  confidence: number;
}

export class ContentGapAnalysisDto {
  @ApiProperty({ description: 'Your site URL' })
  siteUrl: string;

  @ApiProperty({ description: 'Competitor URLs', type: [String] })
  competitors: string[];

  @ApiProperty({ description: 'Content gaps found' })
  gaps: Array<{
    keyword: string;
    yourCoverage: boolean;
    competitorsCovering: number;
    searchVolume: number;
    difficulty: number;
    priority: 'high' | 'medium' | 'low';
    suggestedContentType: string;
  }>;

  @ApiProperty({ description: 'Topic opportunities' })
  topicOpportunities: Array<{
    topic: string;
    description: string;
    estimatedTraffic: number;
    competitionLevel: string;
  }>;

  @ApiProperty({ description: 'Total gaps found' })
  totalGaps: number;

  @ApiProperty({ description: 'High priority gaps' })
  highPriorityGaps: number;

  @ApiProperty({ description: 'Estimated traffic opportunity' })
  estimatedTrafficOpportunity: number;
}

export class CompetitorAnalysisDto {
  @ApiProperty({ description: 'Competitor URL' })
  url: string;

  @ApiProperty({ description: 'Domain authority' })
  domainAuthority: number;

  @ApiProperty({ description: 'Estimated monthly traffic' })
  estimatedTraffic: number;

  @ApiProperty({ description: 'Top ranking keywords' })
  topKeywords: Array<{
    keyword: string;
    position: number;
    searchVolume: number;
  }>;

  @ApiProperty({ description: 'Content analysis' })
  content: {
    totalPages: number;
    avgWordCount: number;
    contentTypes: string[];
  };

  @ApiProperty({ description: 'Backlink profile' })
  backlinks: {
    totalBacklinks: number;
    referringDomains: number;
    topSources: string[];
  };
}

export class AutoGeneratedMetaDto {
  @ApiProperty({ description: 'Generated title' })
  title: string;

  @ApiProperty({ description: 'Generated description' })
  description: string;

  @ApiProperty({ description: 'Extracted keywords', type: [String] })
  keywords: string[];

  @ApiProperty({ description: 'Open Graph data' })
  openGraph: {
    title: string;
    description: string;
    type: string;
  };

  @ApiProperty({ description: 'Twitter Card data' })
  twitterCard: {
    card: 'summary' | 'summary_large_image';
    title: string;
    description: string;
  };

  @ApiProperty({ description: 'Confidence scores' })
  confidence: {
    title: number;
    description: number;
    overall: number;
  };

  @ApiProperty({ description: 'Alternative suggestions' })
  alternatives: {
    titles: string[];
    descriptions: string[];
  };
}

export class SeoRecommendationDto {
  @ApiProperty({ description: 'Recommendation ID' })
  id: string;

  @ApiProperty({ description: 'Category' })
  category: 'content' | 'technical' | 'local' | 'backlinks';

  @ApiProperty({ description: 'Priority level' })
  priority: 'high' | 'medium' | 'low';

  @ApiProperty({ description: 'Title' })
  title: string;

  @ApiProperty({ description: 'Description' })
  description: string;

  @ApiProperty({ description: 'Expected impact' })
  impact: string;

  @ApiProperty({ description: 'Implementation effort' })
  effort: 'low' | 'medium' | 'high';

  @ApiPropertyOptional({ description: 'Estimated traffic gain' })
  estimatedTrafficGain?: number;

  @ApiProperty({ description: 'Implementation steps', type: [String] })
  implementation: string[];
}

export class ContentScoreDto {
  @ApiProperty({ description: 'Overall score (0-100)' })
  overall: number;

  @ApiProperty({ description: 'Content quality score' })
  quality: number;

  @ApiProperty({ description: 'SEO optimization score' })
  seo: number;

  @ApiProperty({ description: 'Readability score' })
  readability: number;

  @ApiProperty({ description: 'Engagement potential score' })
  engagement: number;
}

export class TopicClusterDto {
  @ApiProperty({ description: 'Pillar topic' })
  pillarTopic: string;

  @ApiProperty({ description: 'Pillar content details' })
  pillarContent: {
    title: string;
    description: string;
    targetKeywords: string[];
    estimatedWordCount: number;
  };

  @ApiProperty({ description: 'Cluster topics' })
  clusters: Array<{
    title: string;
    keywords: string[];
    searchVolume: number;
    priority: 'high' | 'medium' | 'low';
    status: 'not_started' | 'in_progress' | 'published';
  }>;

  @ApiProperty({ description: 'Total search volume opportunity' })
  totalSearchVolume: number;

  @ApiProperty({ description: 'Internal linking strategy', type: [String] })
  internalLinkingStrategy: string[];
}

export class ContentBriefDto {
  @ApiProperty({ description: 'Topic' })
  topic: string;

  @ApiProperty({ description: 'Target keywords', type: [String] })
  targetKeywords: string[];

  @ApiProperty({ description: 'Search intent' })
  searchIntent: SearchIntentDto;

  @ApiProperty({ description: 'Content type' })
  contentType: string;

  @ApiProperty({ description: 'Suggested outline' })
  suggestedOutline: Array<{
    heading: string;
    subheadings: string[];
  }>;

  @ApiProperty({ description: 'Related questions', type: [String] })
  relatedQuestions: string[];

  @ApiProperty({ description: 'Recommended word count' })
  recommendedLength: number;

  @ApiProperty({ description: 'Keyword targets' })
  keywordTargets: Array<{
    keyword: string;
    targetDensity: string;
    placement: string[];
  }>;

  @ApiProperty({ description: 'Competitor insights' })
  competitorInsights: {
    avgWordCount: number;
    commonHeadings: string[];
    topRankingFactors: string[];
  };

  @ApiProperty({ description: 'Content guidelines', type: [String] })
  contentGuidelines: string[];

  @ApiProperty({ description: 'Estimated creation time' })
  estimatedTime: string;
}

export enum SeoTaskStatus {
  QUEUED = 'queued',
  PROCESSING = 'processing',
  COMPLETED = 'completed',
  FAILED = 'failed',
}

export class SeoTaskDto {
  @ApiProperty({ description: 'Task ID' })
  id: string;

  @ApiProperty({ description: 'Task type' })
  type: string;

  @ApiProperty({ description: 'Task status', enum: SeoTaskStatus })
  status: SeoTaskStatus;

  @ApiProperty({ description: 'Task data' })
  data: Record<string, any>;

  @ApiProperty({ description: 'Created timestamp' })
  createdAt: string;

  @ApiPropertyOptional({ description: 'Started timestamp' })
  startedAt?: string;

  @ApiPropertyOptional({ description: 'Completed timestamp' })
  completedAt?: string;

  @ApiProperty({ description: 'Progress (0-100)' })
  progress: number;

  @ApiPropertyOptional({ description: 'Task result' })
  result?: Record<string, any>;

  @ApiPropertyOptional({ description: 'Error message' })
  error?: string;
}

// Request DTOs

export class AnalyzeContentRequestDto {
  @ApiProperty({ description: 'Content to analyze' })
  @IsString()
  content: string;

  @ApiProperty({ description: 'Target keywords', type: [String] })
  @IsArray()
  @IsString({ each: true })
  targetKeywords: string[];

  @ApiPropertyOptional({ description: 'Content type' })
  @IsOptional()
  @IsString()
  contentType?: 'product' | 'category' | 'blog' | 'page';
}

export class GenerateKeywordsRequestDto {
  @ApiProperty({ description: 'Seed keywords', type: [String] })
  @IsArray()
  @IsString({ each: true })
  seedKeywords: string[];

  @ApiPropertyOptional({ description: 'Industry/niche' })
  @IsOptional()
  @IsString()
  industry?: string;

  @ApiPropertyOptional({ description: 'Locale', default: 'en-US' })
  @IsOptional()
  @IsString()
  locale?: string;
}

export class ContentGapRequestDto {
  @ApiProperty({ description: 'Your site URL' })
  @IsString()
  siteUrl: string;

  @ApiProperty({ description: 'Competitor URLs', type: [String] })
  @IsArray()
  @IsString({ each: true })
  competitorUrls: string[];

  @ApiPropertyOptional({ description: 'Target keywords', type: [String] })
  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  targetKeywords?: string[];
}

export class AutoGenerateMetaRequestDto {
  @ApiProperty({ description: 'Content to analyze' })
  @IsString()
  content: string;

  @ApiPropertyOptional({ description: 'Product information' })
  @IsOptional()
  @IsObject()
  productInfo?: {
    name: string;
    price?: number;
    brand?: string;
    category?: string;
  };
}

export class ContentBriefRequestDto {
  @ApiProperty({ description: 'Topic' })
  @IsString()
  topic: string;

  @ApiProperty({ description: 'Target keywords', type: [String] })
  @IsArray()
  @IsString({ each: true })
  targetKeywords: string[];

  @ApiPropertyOptional({ description: 'Content type' })
  @IsOptional()
  @IsString()
  contentType?: 'blog' | 'product' | 'category' | 'landing';
}

export class TopicClusterRequestDto {
  @ApiProperty({ description: 'Pillar topic' })
  @IsString()
  pillarTopic: string;

  @ApiPropertyOptional({ description: 'Industry/niche' })
  @IsOptional()
  @IsString()
  industry?: string;
}

export class QueueTaskRequestDto {
  @ApiProperty({ description: 'Task type' })
  @IsString()
  type: 'content_optimization' | 'meta_generation' | 'keyword_research' | 'audit';

  @ApiProperty({ description: 'Task data' })
  @IsObject()
  data: Record<string, any>;
}
