#!/bin/bash
#===============================================================================
# Broxiva GoDaddy VPS - SSL Certificate Setup Script
# Step 6: Configure Let's Encrypt SSL via Certbot
#===============================================================================

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

#===============================================================================
# Configuration
#===============================================================================
DOMAIN="broxiva.com"
WWW_DOMAIN="www.broxiva.com"
API_DOMAIN="api.broxiva.com"
EMAIL="${CERTBOT_EMAIL:-admin@broxiva.com}"

#===============================================================================
# Pre-flight Checks
#===============================================================================
log_info "Starting SSL certificate setup..."

if [[ $EUID -ne 0 ]]; then
   log_error "This script must be run as root"
   exit 1
fi

# Check if domains resolve to this server
SERVER_IP=$(curl -s ifconfig.me)
log_info "Server IP: ${SERVER_IP}"

for domain in $DOMAIN $WWW_DOMAIN $API_DOMAIN; do
    RESOLVED_IP=$(dig +short $domain | head -1)
    if [ "$RESOLVED_IP" != "$SERVER_IP" ]; then
        log_warning "$domain resolves to $RESOLVED_IP (expected $SERVER_IP)"
        log_warning "DNS may not have propagated yet"
    else
        log_success "$domain correctly resolves to this server"
    fi
done

#===============================================================================
# Stop Nginx Temporarily
#===============================================================================
log_info "Stopping Nginx for certificate issuance..."
systemctl stop nginx

#===============================================================================
# Obtain SSL Certificates
#===============================================================================
log_info "Obtaining SSL certificates from Let's Encrypt..."

# Obtain certificate for all domains
certbot certonly \
    --standalone \
    --non-interactive \
    --agree-tos \
    --email "${EMAIL}" \
    -d "${DOMAIN}" \
    -d "${WWW_DOMAIN}" \
    -d "${API_DOMAIN}"

if [ $? -eq 0 ]; then
    log_success "SSL certificates obtained"
else
    log_error "Failed to obtain SSL certificates"
    log_info "Make sure DNS is pointing to this server"
    systemctl start nginx
    exit 1
fi

#===============================================================================
# Generate Strong DH Parameters
#===============================================================================
log_info "Generating Diffie-Hellman parameters (this may take a while)..."

if [ ! -f /etc/nginx/ssl/dhparam.pem ]; then
    mkdir -p /etc/nginx/ssl
    openssl dhparam -out /etc/nginx/ssl/dhparam.pem 2048
    log_success "DH parameters generated"
else
    log_warning "DH parameters already exist"
fi

#===============================================================================
# Create SSL Configuration
#===============================================================================
log_info "Creating SSL configuration..."

cat > /etc/nginx/ssl-params.conf << 'EOF'
# SSL Parameters for Broxiva
# Generated by ssl-setup.sh

# SSL Session Settings
ssl_session_timeout 1d;
ssl_session_cache shared:SSL:50m;
ssl_session_tickets off;

# Modern SSL Configuration
ssl_protocols TLSv1.2 TLSv1.3;
ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
ssl_prefer_server_ciphers off;

# DH Parameters
ssl_dhparam /etc/nginx/ssl/dhparam.pem;

# HSTS (15768000 seconds = 6 months)
add_header Strict-Transport-Security "max-age=15768000; includeSubDomains; preload" always;

# OCSP Stapling
ssl_stapling on;
ssl_stapling_verify on;
resolver 8.8.8.8 8.8.4.4 valid=300s;
resolver_timeout 5s;

# Security Headers
add_header X-Frame-Options DENY always;
add_header X-Content-Type-Options nosniff always;
add_header X-XSS-Protection "1; mode=block" always;
add_header Referrer-Policy "strict-origin-when-cross-origin" always;
EOF

log_success "SSL configuration created"

#===============================================================================
# Update Nginx Configuration
#===============================================================================
log_info "Updating Nginx configuration with SSL..."

# Create Nginx site configuration with SSL
cat > /etc/nginx/sites-available/broxiva << EOF
# Broxiva Nginx Configuration with SSL
# Generated by ssl-setup.sh

# Rate limiting zones
limit_req_zone \$binary_remote_addr zone=general:10m rate=10r/s;
limit_req_zone \$binary_remote_addr zone=api:10m rate=30r/s;
limit_conn_zone \$binary_remote_addr zone=addr:10m;

# Upstream for frontend
upstream frontend {
    server 127.0.0.1:3000;
    keepalive 32;
}

# Upstream for backend
upstream backend {
    server 127.0.0.1:4000;
    keepalive 32;
}

# HTTP to HTTPS redirect
server {
    listen 80;
    listen [::]:80;
    server_name ${DOMAIN} ${WWW_DOMAIN} ${API_DOMAIN};

    # ACME challenge for cert renewal
    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        return 301 https://\$host\$request_uri;
    }
}

# Redirect non-www to www
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name ${DOMAIN};

    ssl_certificate /etc/letsencrypt/live/${DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${DOMAIN}/privkey.pem;
    include /etc/nginx/ssl-params.conf;

    return 301 https://${WWW_DOMAIN}\$request_uri;
}

# Main frontend server (www.broxiva.com)
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name ${WWW_DOMAIN};

    # SSL Configuration
    ssl_certificate /etc/letsencrypt/live/${DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${DOMAIN}/privkey.pem;
    include /etc/nginx/ssl-params.conf;

    # Logging
    access_log /var/log/nginx/broxiva_access.log;
    error_log /var/log/nginx/broxiva_error.log;

    # Gzip compression
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_types text/plain text/css text/xml application/json application/javascript application/rss+xml application/atom+xml image/svg+xml;

    # Rate limiting
    limit_req zone=general burst=20 nodelay;
    limit_conn addr 50;

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://js.stripe.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https: blob:; font-src 'self' data:; connect-src 'self' https://api.broxiva.com wss://api.broxiva.com https://api.stripe.com; frame-src https://js.stripe.com https://hooks.stripe.com;" always;

    # Static files caching
    location /_next/static/ {
        proxy_pass http://frontend;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location /static/ {
        proxy_pass http://frontend;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        expires 30d;
        add_header Cache-Control "public";
    }

    # Next.js frontend
    location / {
        proxy_pass http://frontend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;

        # Timeouts
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }
}

# API server (api.broxiva.com)
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name ${API_DOMAIN};

    # SSL Configuration
    ssl_certificate /etc/letsencrypt/live/${DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${DOMAIN}/privkey.pem;
    include /etc/nginx/ssl-params.conf;

    # Logging
    access_log /var/log/nginx/api_access.log;
    error_log /var/log/nginx/api_error.log;

    # Gzip compression
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_types application/json text/plain;

    # Rate limiting (more generous for API)
    limit_req zone=api burst=50 nodelay;
    limit_conn addr 100;

    # Client body size for file uploads
    client_max_body_size 100M;

    # CORS headers (handled by backend, but ensure preflight works)
    location / {
        # Handle preflight requests
        if (\$request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' 'https://www.broxiva.com' always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, PATCH, OPTIONS' always;
            add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type, X-Requested-With, X-CSRF-Token' always;
            add_header 'Access-Control-Max-Age' 86400 always;
            add_header 'Content-Length' 0;
            add_header 'Content-Type' 'text/plain charset=UTF-8';
            return 204;
        }

        proxy_pass http://backend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;

        # Timeouts for long-running requests
        proxy_connect_timeout 120s;
        proxy_send_timeout 120s;
        proxy_read_timeout 120s;
    }

    # Health check endpoint
    location /api/health {
        proxy_pass http://backend;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        access_log off;
    }

    # WebSocket support
    location /socket.io/ {
        proxy_pass http://backend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;

        # WebSocket timeout
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
    }
}
EOF

# Enable the site
ln -sf /etc/nginx/sites-available/broxiva /etc/nginx/sites-enabled/
rm -f /etc/nginx/sites-enabled/default

# Test configuration
nginx -t
if [ $? -eq 0 ]; then
    log_success "Nginx configuration is valid"
else
    log_error "Nginx configuration test failed"
    exit 1
fi

#===============================================================================
# Start Nginx
#===============================================================================
log_info "Starting Nginx..."
systemctl start nginx
systemctl enable nginx

log_success "Nginx started"

#===============================================================================
# Configure Auto-Renewal
#===============================================================================
log_info "Configuring certificate auto-renewal..."

# Create renewal hook
cat > /etc/letsencrypt/renewal-hooks/post/reload-nginx.sh << 'EOF'
#!/bin/bash
systemctl reload nginx
EOF
chmod +x /etc/letsencrypt/renewal-hooks/post/reload-nginx.sh

# Test renewal
certbot renew --dry-run

log_success "Certificate auto-renewal configured"

#===============================================================================
# Verify SSL
#===============================================================================
log_info "Verifying SSL configuration..."

sleep 2

for domain in $WWW_DOMAIN $API_DOMAIN; do
    if curl -s -o /dev/null -w "%{http_code}" "https://${domain}" | grep -qE "200|301|302"; then
        log_success "HTTPS working for ${domain}"
    else
        log_warning "HTTPS verification needed for ${domain}"
    fi
done

#===============================================================================
# Summary
#===============================================================================
echo ""
echo "==============================================================================="
log_success "SSL Certificate Setup Complete!"
echo "==============================================================================="
echo ""
echo "SSL Configuration:"
echo "  - Certificate: /etc/letsencrypt/live/${DOMAIN}/fullchain.pem"
echo "  - Private Key: /etc/letsencrypt/live/${DOMAIN}/privkey.pem"
echo "  - DH Params: /etc/nginx/ssl/dhparam.pem"
echo ""
echo "Domains Secured:"
echo "  - https://${DOMAIN} (redirects to www)"
echo "  - https://${WWW_DOMAIN} (frontend)"
echo "  - https://${API_DOMAIN} (backend API)"
echo ""
echo "Auto-Renewal:"
echo "  - Certbot timer: Active"
echo "  - Test: certbot renew --dry-run"
echo ""
echo "Nginx Configuration:"
echo "  - Config: /etc/nginx/sites-available/broxiva"
echo "  - Test: nginx -t"
echo "  - Reload: systemctl reload nginx"
echo ""
echo "Next Steps:"
echo "  1. Run ./07-final-verification.sh to verify the complete setup"
echo ""
