# Broxiva DNS Module Outputs
# CRITICAL: These outputs provide the Azure nameservers needed for GoDaddy configuration

# ============================================
# AZURE NAMESERVERS - CONFIGURE IN GODADDY
# ============================================
# After running terraform apply, these nameservers will be generated by Azure.
# You MUST update your GoDaddy nameserver settings to point to these values.
# DNS propagation typically takes 24-48 hours after updating GoDaddy.
# ============================================

output "nameservers" {
  description = "Azure DNS nameservers to configure in GoDaddy. Replace default GoDaddy nameservers with these."
  value       = azurerm_dns_zone.main.name_servers
}

output "nameservers_formatted" {
  description = "Formatted nameservers for easy copy-paste into GoDaddy"
  value = join("\n", [
    "=".repeat(60),
    "BROXIVA.COM AZURE DNS NAMESERVERS",
    "Configure these in GoDaddy > Domain Settings > Nameservers",
    "=".repeat(60),
    "",
    "Nameserver 1: ${try(azurerm_dns_zone.main.name_servers[0], "pending...")}",
    "Nameserver 2: ${try(azurerm_dns_zone.main.name_servers[1], "pending...")}",
    "Nameserver 3: ${try(azurerm_dns_zone.main.name_servers[2], "pending...")}",
    "Nameserver 4: ${try(azurerm_dns_zone.main.name_servers[3], "pending...")}",
    "",
    "=".repeat(60),
    "IMPORTANT: Remove default GoDaddy nameservers and add these",
    "DNS propagation takes 24-48 hours",
    "=".repeat(60)
  ])
}

# ============================================
# DNS Zone Information
# ============================================

output "zone_id" {
  description = "The DNS zone ID"
  value       = azurerm_dns_zone.main.id
}

output "zone_name" {
  description = "The DNS zone name"
  value       = azurerm_dns_zone.main.name
}

output "resource_group_name" {
  description = "The resource group containing the DNS zone"
  value       = var.resource_group_name
}

# ============================================
# Record FQDNs
# ============================================

output "root_fqdn" {
  description = "Fully qualified domain name for root"
  value       = var.domain_name
}

output "www_fqdn" {
  description = "Fully qualified domain name for www"
  value       = "www.${var.domain_name}"
}

output "api_fqdn" {
  description = "Fully qualified domain name for API"
  value       = "api.${var.domain_name}"
}

output "cdn_fqdn" {
  description = "Fully qualified domain name for CDN"
  value       = "cdn.${var.domain_name}"
}

# ============================================
# GoDaddy Configuration Instructions
# ============================================

output "godaddy_instructions" {
  description = "Step-by-step instructions for configuring GoDaddy"
  value = <<-EOT

    ======================================================
    GODADDY NAMESERVER CONFIGURATION FOR BROXIVA.COM
    ======================================================

    STEP 1: Log into GoDaddy
    -------------------------
    1. Go to https://www.godaddy.com
    2. Sign in to your account
    3. Click "My Products" > find broxiva.com

    STEP 2: Access Nameserver Settings
    -----------------------------------
    1. Click "DNS" or "Manage" next to broxiva.com
    2. Scroll to "Nameservers" section
    3. Click "Change" or "Edit"
    4. Select "I'll use my own nameservers"

    STEP 3: Enter Azure Nameservers
    --------------------------------
    Replace ALL existing nameservers with:

    NS1: ${try(azurerm_dns_zone.main.name_servers[0], "Run 'terraform apply' to generate")}
    NS2: ${try(azurerm_dns_zone.main.name_servers[1], "Run 'terraform apply' to generate")}
    NS3: ${try(azurerm_dns_zone.main.name_servers[2], "Run 'terraform apply' to generate")}
    NS4: ${try(azurerm_dns_zone.main.name_servers[3], "Run 'terraform apply' to generate")}

    STEP 4: Save and Wait
    ----------------------
    1. Click "Save" to confirm changes
    2. DNS propagation takes 24-48 hours
    3. Use https://dnschecker.org to verify propagation

    STEP 5: Verify Configuration
    -----------------------------
    Run: nslookup broxiva.com
    Expected: Should resolve to Azure Front Door IP

    ======================================================
    SUPPORT: For issues, check Azure DNS Zone in portal
    ======================================================

  EOT
}

# ============================================
# DNS Verification Commands
# ============================================

output "verification_commands" {
  description = "Commands to verify DNS configuration"
  value = <<-EOT
    # Verify nameservers are updated:
    nslookup -type=NS broxiva.com

    # Verify A record:
    nslookup broxiva.com
    nslookup www.broxiva.com

    # Verify API subdomain:
    nslookup api.broxiva.com

    # Verify CDN subdomain:
    nslookup cdn.broxiva.com

    # Check propagation status:
    # Visit: https://dnschecker.org/#NS/broxiva.com
  EOT
}

# ============================================
# Summary for CI/CD
# ============================================

output "dns_config_summary" {
  description = "Summary of DNS configuration for CI/CD pipelines"
  value = {
    domain          = var.domain_name
    zone_id         = azurerm_dns_zone.main.id
    nameservers     = azurerm_dns_zone.main.name_servers
    subdomains      = ["www", "api", "cdn", "staging", "staging-api", "health"]
    email_enabled   = var.enable_email_records
    caa_enabled     = var.enable_caa_records
    registrar       = "GoDaddy"
    cloud_provider  = "Microsoft Azure"
  }
}
