version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: us-east-1
    NODE_OPTIONS: "--max-old-space-size=8192"

phases:
  install:
    runtime-versions:
      nodejs: 20
      python: 3.11
    commands:
      - echo "Installing build dependencies..."
      - npm install -g pnpm@10
      - pip install --upgrade pip

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - BUILD_DATE=$(date +%Y%m%d)
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - export IMAGE_TAG="${BUILD_DATE}-${COMMIT_HASH}"
      - echo "Build tag is $IMAGE_TAG"

  build:
    commands:
      - echo "===== INSTALLING DEPENDENCIES ====="
      - cd $CODEBUILD_SRC_DIR/organization
      - pnpm install --frozen-lockfile || pnpm install
      - echo "===== GENERATING PRISMA CLIENT ====="
      - cd $CODEBUILD_SRC_DIR/organization/apps/api
      - npx prisma generate
      - echo "===== BUILDING API ====="
      - pnpm build
      - echo "===== BUILDING DOCKER IMAGE FOR API ====="
      - cd $CODEBUILD_SRC_DIR/organization
      - docker build -t broxiva/api:$IMAGE_TAG -f apps/api/Dockerfile .
      - docker tag broxiva/api:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/broxiva/api:$IMAGE_TAG
      - docker tag broxiva/api:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/broxiva/api:latest
      - echo "===== BUILDING WEB ====="
      - cd $CODEBUILD_SRC_DIR/organization/apps/web
      - pnpm build
      - echo "===== BUILDING DOCKER IMAGE FOR WEB ====="
      - cd $CODEBUILD_SRC_DIR/organization
      - docker build -t broxiva/web:$IMAGE_TAG -f apps/web/Dockerfile .
      - docker tag broxiva/web:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/broxiva/web:$IMAGE_TAG
      - docker tag broxiva/web:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/broxiva/web:latest
      - echo "===== BUILDING PYTHON MICROSERVICES ====="
      - cd $CODEBUILD_SRC_DIR/organization
      - |
        for SERVICE in ai-agents ai-engine analytics chatbot fraud-detection inventory media notification personalization pricing recommendation search supplier-integration; do
          echo "===== Building $SERVICE ====="
          SERVICE_PATH="apps/services/$SERVICE"
          if [ -f "$SERVICE_PATH/Dockerfile" ]; then
            docker build -t broxiva/$SERVICE:$IMAGE_TAG -f $SERVICE_PATH/Dockerfile $SERVICE_PATH/
            docker tag broxiva/$SERVICE:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/broxiva/$SERVICE:$IMAGE_TAG
            docker tag broxiva/$SERVICE:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/broxiva/$SERVICE:latest
            echo "$SERVICE built successfully"
          else
            echo "WARNING: Dockerfile not found for $SERVICE at $SERVICE_PATH/Dockerfile"
          fi
        done

  post_build:
    commands:
      - echo "===== PUSHING IMAGES TO ECR ====="
      - echo "Pushing API..."
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/broxiva/api:$IMAGE_TAG
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/broxiva/api:latest
      - echo "Pushing Web..."
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/broxiva/web:$IMAGE_TAG
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/broxiva/web:latest
      - echo "===== PUSHING PYTHON MICROSERVICES ====="
      - |
        for SERVICE in ai-agents ai-engine analytics chatbot fraud-detection inventory media notification personalization pricing recommendation search supplier-integration; do
          echo "Pushing $SERVICE..."
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/broxiva/$SERVICE:$IMAGE_TAG || echo "Failed to push $SERVICE (image may not exist)"
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/broxiva/$SERVICE:latest || echo "Failed to push $SERVICE:latest"
        done
      - echo "===== BUILD COMPLETE ====="
      - cd $CODEBUILD_SRC_DIR
      - |
        cat > imagedefinitions.json << EOF
        [
          {"name":"api","imageUri":"$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/broxiva/api:$IMAGE_TAG"},
          {"name":"web","imageUri":"$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/broxiva/web:$IMAGE_TAG"},
          {"name":"ai-agents","imageUri":"$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/broxiva/ai-agents:$IMAGE_TAG"},
          {"name":"ai-engine","imageUri":"$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/broxiva/ai-engine:$IMAGE_TAG"},
          {"name":"analytics","imageUri":"$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/broxiva/analytics:$IMAGE_TAG"},
          {"name":"chatbot","imageUri":"$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/broxiva/chatbot:$IMAGE_TAG"},
          {"name":"fraud-detection","imageUri":"$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/broxiva/fraud-detection:$IMAGE_TAG"},
          {"name":"inventory","imageUri":"$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/broxiva/inventory:$IMAGE_TAG"},
          {"name":"media","imageUri":"$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/broxiva/media:$IMAGE_TAG"},
          {"name":"notification","imageUri":"$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/broxiva/notification:$IMAGE_TAG"},
          {"name":"personalization","imageUri":"$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/broxiva/personalization:$IMAGE_TAG"},
          {"name":"pricing","imageUri":"$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/broxiva/pricing:$IMAGE_TAG"},
          {"name":"recommendation","imageUri":"$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/broxiva/recommendation:$IMAGE_TAG"},
          {"name":"search","imageUri":"$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/broxiva/search:$IMAGE_TAG"},
          {"name":"supplier-integration","imageUri":"$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/broxiva/supplier-integration:$IMAGE_TAG"}
        ]
        EOF
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
  discard-paths: yes

cache:
  paths:
    - organization/node_modules/**/*
