version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: us-east-1
    NODE_OPTIONS: "--max-old-space-size=8192"

phases:
  install:
    runtime-versions:
      nodejs: 20
      python: 3.11
    commands:
      - echo "Installing build dependencies..."
      - npm install -g pnpm@10
      - pip install --upgrade pip

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - BUILD_DATE=$(date +%Y%m%d)
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - export IMAGE_TAG="${BUILD_DATE}-${COMMIT_HASH}"
      - echo "Build tag is $IMAGE_TAG"

  build:
    commands:
      - echo "===== INSTALLING DEPENDENCIES ====="
      - cd $CODEBUILD_SRC_DIR/organization
      - pnpm install --frozen-lockfile || pnpm install
      - echo "===== GENERATING PRISMA CLIENT ====="
      - cd $CODEBUILD_SRC_DIR/organization/apps/api
      - npx prisma generate
      - echo "===== BUILDING API ====="
      - pnpm build
      - echo "===== BUILDING DOCKER IMAGE FOR API ====="
      - cd $CODEBUILD_SRC_DIR/organization
      - docker build -t broxiva/api:$IMAGE_TAG -f apps/api/Dockerfile .
      - docker tag broxiva/api:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/broxiva/api:$IMAGE_TAG
      - docker tag broxiva/api:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/broxiva/api:latest
      - echo "===== BUILDING WEB ====="
      - cd $CODEBUILD_SRC_DIR/organization/apps/web
      - pnpm build
      - echo "===== BUILDING DOCKER IMAGE FOR WEB ====="
      - cd $CODEBUILD_SRC_DIR/organization
      - docker build -t broxiva/web:$IMAGE_TAG -f apps/web/Dockerfile .
      - docker tag broxiva/web:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/broxiva/web:$IMAGE_TAG
      - docker tag broxiva/web:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/broxiva/web:latest

  post_build:
    commands:
      - echo "===== PUSHING IMAGES TO ECR ====="
      - echo "Pushing API..."
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/broxiva/api:$IMAGE_TAG
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/broxiva/api:latest
      - echo "Pushing Web..."
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/broxiva/web:$IMAGE_TAG
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/broxiva/web:latest
      - echo "===== BUILD COMPLETE ====="
      - cd $CODEBUILD_SRC_DIR
      - printf '[{"name":"api","imageUri":"%s"},{"name":"web","imageUri":"%s"}]' "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/broxiva/api:$IMAGE_TAG" "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/broxiva/web:$IMAGE_TAG" > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
  discard-paths: yes

cache:
  paths:
    - organization/node_modules/**/*
