# Docker Build and Push Stage
# Builds and pushes all CitadelBuy container images to Azure Container Registry

parameters:
  - name: registry
    type: string
    default: 'citadelbuyacr.azurecr.io'
    displayName: 'Container registry'

  - name: serviceConnection
    type: string
    default: 'CitadelBuyACR'
    displayName: 'ACR service connection name'

  - name: runSecurityScan
    type: boolean
    default: true
    displayName: 'Run Trivy security scans'

  - name: buildAllServices
    type: boolean
    default: true
    displayName: 'Build all microservices'

stages:
  - stage: DockerBuild
    displayName: 'Docker Build and Push'
    dependsOn: []

    jobs:
      # API Service
      - template: ../jobs/docker-build-push.yml
        parameters:
          imageName: 'citadelbuy/api'
          dockerfilePath: '$(Build.SourcesDirectory)/CitadelBuy/organization/apps/api/Dockerfile.production'
          dockerContext: '$(Build.SourcesDirectory)/CitadelBuy/organization'
          buildArgs: '--build-arg NODE_ENV=production --build-arg BUILD_ID=$(Build.BuildId)'
          scanImage: ${{ parameters.runSecurityScan }}
          registry: ${{ parameters.registry }}
          serviceConnection: ${{ parameters.serviceConnection }}

      # Web Application
      - template: ../jobs/docker-build-push.yml
        parameters:
          imageName: 'citadelbuy/web'
          dockerfilePath: '$(Build.SourcesDirectory)/CitadelBuy/organization/apps/web/Dockerfile.production'
          dockerContext: '$(Build.SourcesDirectory)/CitadelBuy/organization'
          buildArgs: '--build-arg NODE_ENV=production --build-arg BUILD_ID=$(Build.BuildId)'
          scanImage: ${{ parameters.runSecurityScan }}
          registry: ${{ parameters.registry }}
          serviceConnection: ${{ parameters.serviceConnection }}

      # Inventory Service
      - template: ../jobs/docker-build-push.yml
        parameters:
          imageName: 'citadelbuy/inventory-service'
          dockerfilePath: '$(Build.SourcesDirectory)/CitadelBuy/organization/apps/services/inventory/Dockerfile'
          dockerContext: '$(Build.SourcesDirectory)/CitadelBuy/organization/apps/services/inventory'
          buildArgs: '--build-arg NODE_ENV=production'
          scanImage: ${{ parameters.runSecurityScan }}
          registry: ${{ parameters.registry }}
          serviceConnection: ${{ parameters.serviceConnection }}

      # Media Service
      - template: ../jobs/docker-build-push.yml
        parameters:
          imageName: 'citadelbuy/media-service'
          dockerfilePath: '$(Build.SourcesDirectory)/CitadelBuy/organization/apps/services/media/Dockerfile'
          dockerContext: '$(Build.SourcesDirectory)/CitadelBuy/organization/apps/services/media'
          buildArgs: '--build-arg NODE_ENV=production'
          scanImage: ${{ parameters.runSecurityScan }}
          registry: ${{ parameters.registry }}
          serviceConnection: ${{ parameters.serviceConnection }}

      # Notification Service
      - template: ../jobs/docker-build-push.yml
        parameters:
          imageName: 'citadelbuy/notification-service'
          dockerfilePath: '$(Build.SourcesDirectory)/CitadelBuy/organization/apps/services/notification/Dockerfile'
          dockerContext: '$(Build.SourcesDirectory)/CitadelBuy/organization/apps/services/notification'
          buildArgs: '--build-arg NODE_ENV=production'
          scanImage: ${{ parameters.runSecurityScan }}
          registry: ${{ parameters.registry }}
          serviceConnection: ${{ parameters.serviceConnection }}

      # Personalization Service
      - template: ../jobs/docker-build-push.yml
        parameters:
          imageName: 'citadelbuy/personalization-service'
          dockerfilePath: '$(Build.SourcesDirectory)/CitadelBuy/organization/apps/services/personalization/Dockerfile'
          dockerContext: '$(Build.SourcesDirectory)/CitadelBuy/organization/apps/services/personalization'
          buildArgs: '--build-arg NODE_ENV=production'
          scanImage: ${{ parameters.runSecurityScan }}
          registry: ${{ parameters.registry }}
          serviceConnection: ${{ parameters.serviceConnection }}

      # Additional Microservices (Optional - controlled by buildAllServices parameter)
      - ${{ if eq(parameters.buildAllServices, true) }}:
        # AI Agents Service
        - template: ../jobs/docker-build-push.yml
          parameters:
            imageName: 'citadelbuy/ai-agents-service'
            dockerfilePath: '$(Build.SourcesDirectory)/CitadelBuy/organization/apps/services/ai-agents/Dockerfile'
            dockerContext: '$(Build.SourcesDirectory)/CitadelBuy/organization/apps/services/ai-agents'
            buildArgs: '--build-arg NODE_ENV=production'
            scanImage: ${{ parameters.runSecurityScan }}
            registry: ${{ parameters.registry }}
            serviceConnection: ${{ parameters.serviceConnection }}

        # AI Engine Service
        - template: ../jobs/docker-build-push.yml
          parameters:
            imageName: 'citadelbuy/ai-engine-service'
            dockerfilePath: '$(Build.SourcesDirectory)/CitadelBuy/organization/apps/services/ai-engine/Dockerfile'
            dockerContext: '$(Build.SourcesDirectory)/CitadelBuy/organization/apps/services/ai-engine'
            buildArgs: '--build-arg NODE_ENV=production'
            scanImage: ${{ parameters.runSecurityScan }}
            registry: ${{ parameters.registry }}
            serviceConnection: ${{ parameters.serviceConnection }}

        # Analytics Service
        - template: ../jobs/docker-build-push.yml
          parameters:
            imageName: 'citadelbuy/analytics-service'
            dockerfilePath: '$(Build.SourcesDirectory)/CitadelBuy/organization/apps/services/analytics/Dockerfile'
            dockerContext: '$(Build.SourcesDirectory)/CitadelBuy/organization/apps/services/analytics'
            buildArgs: '--build-arg NODE_ENV=production'
            scanImage: ${{ parameters.runSecurityScan }}
            registry: ${{ parameters.registry }}
            serviceConnection: ${{ parameters.serviceConnection }}

        # Chatbot Service
        - template: ../jobs/docker-build-push.yml
          parameters:
            imageName: 'citadelbuy/chatbot-service'
            dockerfilePath: '$(Build.SourcesDirectory)/CitadelBuy/organization/apps/services/chatbot/Dockerfile'
            dockerContext: '$(Build.SourcesDirectory)/CitadelBuy/organization/apps/services/chatbot'
            buildArgs: '--build-arg NODE_ENV=production'
            scanImage: ${{ parameters.runSecurityScan }}
            registry: ${{ parameters.registry }}
            serviceConnection: ${{ parameters.serviceConnection }}

        # Fraud Detection Service
        - template: ../jobs/docker-build-push.yml
          parameters:
            imageName: 'citadelbuy/fraud-detection-service'
            dockerfilePath: '$(Build.SourcesDirectory)/CitadelBuy/organization/apps/services/fraud-detection/Dockerfile'
            dockerContext: '$(Build.SourcesDirectory)/CitadelBuy/organization/apps/services/fraud-detection'
            buildArgs: '--build-arg NODE_ENV=production'
            scanImage: ${{ parameters.runSecurityScan }}
            registry: ${{ parameters.registry }}
            serviceConnection: ${{ parameters.serviceConnection }}

        # Pricing Service
        - template: ../jobs/docker-build-push.yml
          parameters:
            imageName: 'citadelbuy/pricing-service'
            dockerfilePath: '$(Build.SourcesDirectory)/CitadelBuy/organization/apps/services/pricing/Dockerfile'
            dockerContext: '$(Build.SourcesDirectory)/CitadelBuy/organization/apps/services/pricing'
            buildArgs: '--build-arg NODE_ENV=production'
            scanImage: ${{ parameters.runSecurityScan }}
            registry: ${{ parameters.registry }}
            serviceConnection: ${{ parameters.serviceConnection }}

        # Recommendation Service
        - template: ../jobs/docker-build-push.yml
          parameters:
            imageName: 'citadelbuy/recommendation-service'
            dockerfilePath: '$(Build.SourcesDirectory)/CitadelBuy/organization/apps/services/recommendation/Dockerfile'
            dockerContext: '$(Build.SourcesDirectory)/CitadelBuy/organization/apps/services/recommendation'
            buildArgs: '--build-arg NODE_ENV=production'
            scanImage: ${{ parameters.runSecurityScan }}
            registry: ${{ parameters.registry }}
            serviceConnection: ${{ parameters.serviceConnection }}

        # Search Service
        - template: ../jobs/docker-build-push.yml
          parameters:
            imageName: 'citadelbuy/search-service'
            dockerfilePath: '$(Build.SourcesDirectory)/CitadelBuy/organization/apps/services/search/Dockerfile'
            dockerContext: '$(Build.SourcesDirectory)/CitadelBuy/organization/apps/services/search'
            buildArgs: '--build-arg NODE_ENV=production'
            scanImage: ${{ parameters.runSecurityScan }}
            registry: ${{ parameters.registry }}
            serviceConnection: ${{ parameters.serviceConnection }}

        # Supplier Integration Service
        - template: ../jobs/docker-build-push.yml
          parameters:
            imageName: 'citadelbuy/supplier-integration-service'
            dockerfilePath: '$(Build.SourcesDirectory)/CitadelBuy/organization/apps/services/supplier-integration/Dockerfile'
            dockerContext: '$(Build.SourcesDirectory)/CitadelBuy/organization/apps/services/supplier-integration'
            buildArgs: '--build-arg NODE_ENV=production'
            scanImage: ${{ parameters.runSecurityScan }}
            registry: ${{ parameters.registry }}
            serviceConnection: ${{ parameters.serviceConnection }}

    # Summary Job
    jobs:
      - job: BuildSummary
        displayName: 'Build Summary'
        dependsOn:
          - Build_citadelbuy_api
          - Build_citadelbuy_web
          - Build_citadelbuy_inventory_service
          - Build_citadelbuy_media_service
          - Build_citadelbuy_notification_service
          - Build_citadelbuy_personalization_service
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - pwsh: |
              Write-Host "##[section]====================================="
              Write-Host "##[section]CitadelBuy Docker Build Summary"
              Write-Host "##[section]====================================="
              Write-Host ""
              Write-Host "Registry: ${{ parameters.registry }}"
              Write-Host "Build ID: $(Build.BuildId)"
              Write-Host "Source Version: $(Build.SourceVersion)"
              Write-Host "Branch: $(Build.SourceBranchName)"
              Write-Host ""
              Write-Host "##[section]Images Built and Pushed:"
              Write-Host "  - citadelbuy/api"
              Write-Host "  - citadelbuy/web"
              Write-Host "  - citadelbuy/inventory-service"
              Write-Host "  - citadelbuy/media-service"
              Write-Host "  - citadelbuy/notification-service"
              Write-Host "  - citadelbuy/personalization-service"
              Write-Host ""
              Write-Host "##[section]Image Tags Applied:"
              $shortSha = "$(Build.SourceVersion)".Substring(0, 7)
              Write-Host "  - $shortSha (commit SHA)"
              Write-Host "  - $(Build.SourceBranchName) (branch)"
              Write-Host "  - latest"
              Write-Host "  - $(Build.BuildId) (build ID)"
              Write-Host ""
              Write-Host "##[section]====================================="
            displayName: 'Display Build Summary'
            condition: always()
