# Terraform Infrastructure as Code Stage
# Handles Terraform plan and apply operations for infrastructure deployment

parameters:
- name: environment
  type: string
  displayName: 'Target Environment'
  values:
  - dev
  - staging
  - prod

- name: serviceConnection
  type: string
  displayName: 'Azure Service Connection'
  default: 'CitadelBuy-Azure-ServiceConnection'

- name: terraformVersion
  type: string
  displayName: 'Terraform Version'
  default: '1.6.0'

- name: autoApprove
  type: boolean
  displayName: 'Auto Approve Apply'
  default: false

- name: destroyMode
  type: boolean
  displayName: 'Destroy Infrastructure'
  default: false

stages:
- stage: Terraform_${{ parameters.environment }}
  displayName: 'Terraform - ${{ upper(parameters.environment) }}'

  variables:
  - template: ../variables/terraform.yml
  - name: workingDirectory
    value: '$(Build.SourcesDirectory)/infrastructure/terraform/environments/${{ parameters.environment }}'
  - name: environment
    value: '${{ parameters.environment }}'

  jobs:
  # Terraform Plan - Always runs to show what changes will be made
  - job: TerraformPlan
    displayName: 'Terraform Plan'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self
      displayName: 'Checkout Repository'
      fetchDepth: 1

    - task: TerraformInstaller@0
      displayName: 'Install Terraform ${{ parameters.terraformVersion }}'
      inputs:
        terraformVersion: '${{ parameters.terraformVersion }}'

    - task: AzureCLI@2
      displayName: 'Terraform Init'
      inputs:
        azureSubscription: '${{ parameters.serviceConnection }}'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        workingDirectory: '$(workingDirectory)'
        addSpnToEnvironment: true
        inlineScript: |
          echo "##[section]Initializing Terraform backend..."

          # Set Azure provider credentials from service principal
          export ARM_SUBSCRIPTION_ID="$(ARM_SUBSCRIPTION_ID)"
          export ARM_TENANT_ID="$(ARM_TENANT_ID)"
          export ARM_CLIENT_ID="$servicePrincipalId"
          export ARM_CLIENT_SECRET="$servicePrincipalKey"

          # Initialize Terraform with backend configuration
          terraform init \
            -backend-config="resource_group_name=$(TF_BACKEND_RESOURCE_GROUP)" \
            -backend-config="storage_account_name=$(TF_BACKEND_STORAGE_ACCOUNT)" \
            -backend-config="container_name=$(TF_BACKEND_CONTAINER)" \
            -backend-config="key=${{ parameters.environment }}/$(TF_BACKEND_KEY)" \
            -reconfigure

          echo "##[section]Terraform initialized successfully"

    - task: AzureCLI@2
      displayName: 'Terraform Validate'
      inputs:
        azureSubscription: '${{ parameters.serviceConnection }}'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        workingDirectory: '$(workingDirectory)'
        addSpnToEnvironment: true
        inlineScript: |
          echo "##[section]Validating Terraform configuration..."

          export ARM_SUBSCRIPTION_ID="$(ARM_SUBSCRIPTION_ID)"
          export ARM_TENANT_ID="$(ARM_TENANT_ID)"
          export ARM_CLIENT_ID="$servicePrincipalId"
          export ARM_CLIENT_SECRET="$servicePrincipalKey"

          terraform validate

          echo "##[section]Terraform configuration is valid"

    - task: AzureCLI@2
      displayName: 'Terraform Plan'
      inputs:
        azureSubscription: '${{ parameters.serviceConnection }}'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        workingDirectory: '$(workingDirectory)'
        addSpnToEnvironment: true
        inlineScript: |
          echo "##[section]Creating Terraform execution plan..."

          export ARM_SUBSCRIPTION_ID="$(ARM_SUBSCRIPTION_ID)"
          export ARM_TENANT_ID="$(ARM_TENANT_ID)"
          export ARM_CLIENT_ID="$servicePrincipalId"
          export ARM_CLIENT_SECRET="$servicePrincipalKey"

          # Set additional variables
          export TF_VAR_environment="${{ parameters.environment }}"
          export TF_VAR_azure_subscription_id="$(ARM_SUBSCRIPTION_ID)"

          # Create plan based on mode
          if [ "${{ parameters.destroyMode }}" = "True" ]; then
            echo "##[warning]Running in DESTROY mode - this will destroy infrastructure!"
            terraform plan -destroy -out=tfplan -input=false
          else
            terraform plan -out=tfplan -input=false
          fi

          # Show plan in readable format
          echo "##[section]Terraform Plan Output:"
          terraform show -no-color tfplan

          # Save plan output for artifact
          terraform show -no-color tfplan > tfplan.txt

          echo "##[section]Terraform plan created successfully"

    - task: PublishPipelineArtifact@1
      displayName: 'Publish Terraform Plan'
      inputs:
        targetPath: '$(workingDirectory)'
        artifact: 'terraform-plan-${{ parameters.environment }}'
        publishLocation: 'pipeline'

    - task: PublishPipelineArtifact@1
      displayName: 'Publish Plan Output'
      inputs:
        targetPath: '$(workingDirectory)/tfplan.txt'
        artifact: 'terraform-plan-output-${{ parameters.environment }}'
        publishLocation: 'pipeline'

  # Terraform Apply - Only runs on main branch or when explicitly triggered
  - job: TerraformApply
    displayName: 'Terraform Apply'
    dependsOn: TerraformPlan
    condition: |
      and(
        succeeded(),
        or(
          and(
            eq(variables['Build.SourceBranch'], 'refs/heads/main'),
            ne(variables['Build.Reason'], 'PullRequest')
          ),
          eq('${{ parameters.autoApprove }}', 'true')
        )
      )
    pool:
      vmImage: 'ubuntu-latest'

    # Add environment for manual approval gates (configured in Azure DevOps)
    environment: '${{ parameters.environment }}'

    steps:
    - checkout: self
      displayName: 'Checkout Repository'
      fetchDepth: 1

    - task: DownloadPipelineArtifact@2
      displayName: 'Download Terraform Plan'
      inputs:
        buildType: 'current'
        artifactName: 'terraform-plan-${{ parameters.environment }}'
        targetPath: '$(workingDirectory)'

    - task: TerraformInstaller@0
      displayName: 'Install Terraform ${{ parameters.terraformVersion }}'
      inputs:
        terraformVersion: '${{ parameters.terraformVersion }}'

    - task: AzureCLI@2
      displayName: 'Terraform Init'
      inputs:
        azureSubscription: '${{ parameters.serviceConnection }}'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        workingDirectory: '$(workingDirectory)'
        addSpnToEnvironment: true
        inlineScript: |
          echo "##[section]Re-initializing Terraform..."

          export ARM_SUBSCRIPTION_ID="$(ARM_SUBSCRIPTION_ID)"
          export ARM_TENANT_ID="$(ARM_TENANT_ID)"
          export ARM_CLIENT_ID="$servicePrincipalId"
          export ARM_CLIENT_SECRET="$servicePrincipalKey"

          terraform init \
            -backend-config="resource_group_name=$(TF_BACKEND_RESOURCE_GROUP)" \
            -backend-config="storage_account_name=$(TF_BACKEND_STORAGE_ACCOUNT)" \
            -backend-config="container_name=$(TF_BACKEND_CONTAINER)" \
            -backend-config="key=${{ parameters.environment }}/$(TF_BACKEND_KEY)" \
            -reconfigure

    - task: AzureCLI@2
      displayName: 'Terraform Apply'
      inputs:
        azureSubscription: '${{ parameters.serviceConnection }}'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        workingDirectory: '$(workingDirectory)'
        addSpnToEnvironment: true
        inlineScript: |
          echo "##[section]Applying Terraform plan..."

          export ARM_SUBSCRIPTION_ID="$(ARM_SUBSCRIPTION_ID)"
          export ARM_TENANT_ID="$(ARM_TENANT_ID)"
          export ARM_CLIENT_ID="$servicePrincipalId"
          export ARM_CLIENT_SECRET="$servicePrincipalKey"

          # Apply the plan
          terraform apply -auto-approve tfplan

          echo "##[section]Terraform apply completed successfully"

    - task: AzureCLI@2
      displayName: 'Terraform Output'
      inputs:
        azureSubscription: '${{ parameters.serviceConnection }}'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        workingDirectory: '$(workingDirectory)'
        addSpnToEnvironment: true
        inlineScript: |
          echo "##[section]Terraform Outputs:"

          export ARM_SUBSCRIPTION_ID="$(ARM_SUBSCRIPTION_ID)"
          export ARM_TENANT_ID="$(ARM_TENANT_ID)"
          export ARM_CLIENT_ID="$servicePrincipalId"
          export ARM_CLIENT_SECRET="$servicePrincipalKey"

          terraform output -json > terraform-outputs.json
          terraform output

          echo "##[section]Outputs saved to artifact"

    - task: PublishPipelineArtifact@1
      displayName: 'Publish Terraform Outputs'
      inputs:
        targetPath: '$(workingDirectory)/terraform-outputs.json'
        artifact: 'terraform-outputs-${{ parameters.environment }}'
        publishLocation: 'pipeline'
