# Testing stage
# Runs API tests with database services, web tests, and mobile tests

parameters:
  - name: nodeVersion
    type: string
    default: '20'
  - name: pnpmVersion
    type: string
    default: '10.23.0'
  - name: workingDirectory
    type: string
    default: '$(System.DefaultWorkingDirectory)'
  - name: runAPITests
    type: boolean
    default: true
  - name: runWebTests
    type: boolean
    default: true
  - name: runMobileTests
    type: boolean
    default: false
  - name: postgresVersion
    type: string
    default: '16-alpine'
  - name: redisVersion
    type: string
    default: '7-alpine'
  - name: databaseUrl
    type: string
    default: 'postgresql://postgres:postgres@localhost:5432/citadelbuy_test'
  - name: redisUrl
    type: string
    default: 'redis://localhost:6379'
  - name: jwtSecret
    type: string
    default: 'test-jwt-secret-key-change-in-production'

stages:
  - stage: Test
    displayName: 'Testing'
    jobs:
      - job: APITests
        displayName: 'API Tests with Database Services'
        condition: eq('${{ parameters.runAPITests }}', true)
        pool:
          vmImage: 'ubuntu-latest'

        services:
          postgres:
            image: postgres:${{ parameters.postgresVersion }}
            ports:
              - 5432:5432
            env:
              POSTGRES_USER: postgres
              POSTGRES_PASSWORD: postgres
              POSTGRES_DB: citadelbuy_test
            options: >-
              --health-cmd pg_isready
              --health-interval 10s
              --health-timeout 5s
              --health-retries 5

          redis:
            image: redis:${{ parameters.redisVersion }}
            ports:
              - 6379:6379
            options: >-
              --health-cmd "redis-cli ping"
              --health-interval 10s
              --health-timeout 5s
              --health-retries 5

        steps:
          - checkout: self
            displayName: 'Checkout code'

          - template: ../jobs/setup-node.yml
            parameters:
              nodeVersion: ${{ parameters.nodeVersion }}
              pnpmVersion: ${{ parameters.pnpmVersion }}
              workingDirectory: ${{ parameters.workingDirectory }}

          - script: |
              pnpm --filter @citadelbuy/api run prisma:generate
            displayName: 'Generate Prisma client'
            workingDirectory: ${{ parameters.workingDirectory }}
            env:
              DATABASE_URL: ${{ parameters.databaseUrl }}

          - script: |
              pnpm --filter @citadelbuy/api run prisma:migrate:deploy
            displayName: 'Run Prisma migrations'
            workingDirectory: ${{ parameters.workingDirectory }}
            env:
              DATABASE_URL: ${{ parameters.databaseUrl }}

          - script: |
              pnpm --filter @citadelbuy/api run test:ci
            displayName: 'Run API tests'
            workingDirectory: ${{ parameters.workingDirectory }}
            env:
              DATABASE_URL: ${{ parameters.databaseUrl }}
              REDIS_URL: ${{ parameters.redisUrl }}
              JWT_SECRET: ${{ parameters.jwtSecret }}
              NODE_ENV: test

          - task: PublishTestResults@2
            displayName: 'Publish API test results'
            condition: always()
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: '**/api/junit.xml'
              testRunTitle: 'API Test Results'
              failTaskOnFailedTests: true

          - task: PublishCodeCoverageResults@2
            displayName: 'Publish API code coverage'
            condition: always()
            inputs:
              codeCoverageTool: 'Cobertura'
              summaryFileLocation: '**/api/coverage/cobertura-coverage.xml'
              reportDirectory: '**/api/coverage'
              failIfCoverageEmpty: false

      - job: WebTests
        displayName: 'Web Frontend Tests (Next.js)'
        condition: eq('${{ parameters.runWebTests }}', true)
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
            displayName: 'Checkout code'

          - template: ../jobs/setup-node.yml
            parameters:
              nodeVersion: ${{ parameters.nodeVersion }}
              pnpmVersion: ${{ parameters.pnpmVersion }}
              workingDirectory: ${{ parameters.workingDirectory }}

          - script: |
              pnpm --filter @citadelbuy/web run test:ci
            displayName: 'Run web tests'
            workingDirectory: ${{ parameters.workingDirectory }}
            env:
              NODE_ENV: test

          - task: PublishTestResults@2
            displayName: 'Publish web test results'
            condition: always()
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: '**/web/junit.xml'
              testRunTitle: 'Web Test Results'
              failTaskOnFailedTests: true

          - task: PublishCodeCoverageResults@2
            displayName: 'Publish web code coverage'
            condition: always()
            inputs:
              codeCoverageTool: 'Cobertura'
              summaryFileLocation: '**/web/coverage/cobertura-coverage.xml'
              reportDirectory: '**/web/coverage'
              failIfCoverageEmpty: false

      - job: MobileTests
        displayName: 'Mobile Tests (React Native)'
        condition: eq('${{ parameters.runMobileTests }}', true)
        pool:
          vmImage: 'macos-latest'
        steps:
          - checkout: self
            displayName: 'Checkout code'

          - template: ../jobs/setup-node.yml
            parameters:
              nodeVersion: ${{ parameters.nodeVersion }}
              pnpmVersion: ${{ parameters.pnpmVersion }}
              workingDirectory: ${{ parameters.workingDirectory }}

          - script: |
              pnpm --filter @citadelbuy/mobile run test:ci
            displayName: 'Run mobile tests'
            workingDirectory: ${{ parameters.workingDirectory }}
            env:
              NODE_ENV: test

          - task: PublishTestResults@2
            displayName: 'Publish mobile test results'
            condition: always()
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: '**/mobile/junit.xml'
              testRunTitle: 'Mobile Test Results'
              failTaskOnFailedTests: true

          - task: PublishCodeCoverageResults@2
            displayName: 'Publish mobile code coverage'
            condition: always()
            inputs:
              codeCoverageTool: 'Cobertura'
              summaryFileLocation: '**/mobile/coverage/cobertura-coverage.xml'
              reportDirectory: '**/mobile/coverage'
              failIfCoverageEmpty: false
