export * from './sitemap.dto';
export * from './robots.dto';
export * from './schema.dto';
export * from './audit.dto';
export * from './vitals.dto';
export * from './technical.dto';
export * from './content-seo.dto';

// New SEO modules - explicit exports to avoid conflicts
export {
  RedirectType,
  RedirectStatus,
  RedirectDto,
  CreateRedirectDto,
  UpdateRedirectDto,
  RedirectQueryDto,
  RedirectBulkItemDto,
  RedirectBulkImportDto,
  RedirectChainDto as RedirectChainDtoNew,
  RedirectAnalyticsDto,
  RedirectValidationResultDto,
  RedirectTestDto,
  RedirectExportDto,
} from './redirects.dto';

export {
  DeviceType as GSCDeviceType,
  SearchType,
  AggregationType,
  SearchConsoleQueryDto,
  SearchAnalyticsFilterDto,
  SearchPerformanceDto,
  SearchQueryDataDto,
  PagePerformanceDto,
  SitemapStatusDto,
  CrawlErrorDto,
  IndexCoverageReportDto,
  SubmitSitemapDto,
  InspectUrlDto,
  RequestIndexingDto,
  OAuthCallbackDto,
} from './search-console.dto';

export * from './meta-tags.dto';
export * from './local-seo.dto';

export {
  ContentOptimizationDto as AIContentOptimizationDto,
  KeywordSuggestionDto,
  SearchIntentDto,
  ContentGapAnalysisDto,
  CompetitorAnalysisDto,
  AutoGeneratedMetaDto,
  SeoRecommendationDto,
  ContentScoreDto,
  TopicClusterDto,
  ContentBriefDto,
  SeoTaskStatus,
  SeoTaskDto,
  AnalyzeContentRequestDto,
  GenerateKeywordsRequestDto,
  ContentGapRequestDto,
  AutoGenerateMetaRequestDto,
  ContentBriefRequestDto,
  TopicClusterRequestDto,
  QueueTaskRequestDto,
} from './ai-seo.dto';

export * from './dashboard.dto';
