# ==========================================
# CitadelBuy - Python Services Continuous Deployment
# Deploys all Python microservices to AKS
# Services: ai-agents, inventory, media, notification, personalization
# ==========================================

trigger:
  branches:
    include:
      - main
      - master
      - develop
  paths:
    include:
      - 'apps/services/**'
      - '.azuredevops/pipelines/cd-services.yml'

pr: none

variables:
  - group: citadelbuy-common
  - group: citadelbuy-acr
  - name: containerRegistry
    value: 'citadelbuyprod.azurecr.io'
  - name: tag
    value: '$(Build.BuildNumber)'
  - name: pythonVersion
    value: '3.11'

stages:
  # ==========================================
  # Stage 1: Build All Python Services
  # ==========================================
  - stage: BuildServices
    displayName: 'Build Python Services'
    jobs:
      # AI Agents Service
      - job: BuildAIAgents
        displayName: 'Build AI Agents Service'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
            fetchDepth: 1

          - task: Docker@2
            displayName: 'Login to ACR'
            inputs:
              command: login
              containerRegistry: 'citadelbuy-acr-connection'

          - task: Docker@2
            displayName: 'Build & Push AI Agents'
            inputs:
              command: buildAndPush
              repository: 'citadelbuy-ai-agents'
              dockerfile: '$(Build.SourcesDirectory)/apps/services/ai-agents/Dockerfile'
              containerRegistry: 'citadelbuy-acr-connection'
              tags: |
                $(tag)

      # Inventory Service
      - job: BuildInventory
        displayName: 'Build Inventory Service'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
            fetchDepth: 1

          - task: Docker@2
            displayName: 'Login to ACR'
            inputs:
              command: login
              containerRegistry: 'citadelbuy-acr-connection'

          - task: Docker@2
            displayName: 'Build & Push Inventory'
            inputs:
              command: buildAndPush
              repository: 'citadelbuy-inventory'
              dockerfile: '$(Build.SourcesDirectory)/apps/services/inventory/Dockerfile'
              containerRegistry: 'citadelbuy-acr-connection'
              tags: |
                $(tag)

      # Media Service
      - job: BuildMedia
        displayName: 'Build Media Service'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
            fetchDepth: 1

          - task: Docker@2
            displayName: 'Login to ACR'
            inputs:
              command: login
              containerRegistry: 'citadelbuy-acr-connection'

          - task: Docker@2
            displayName: 'Build & Push Media'
            inputs:
              command: buildAndPush
              repository: 'citadelbuy-media'
              dockerfile: '$(Build.SourcesDirectory)/apps/services/media/Dockerfile'
              containerRegistry: 'citadelbuy-acr-connection'
              tags: |
                $(tag)

      # Notification Service
      - job: BuildNotification
        displayName: 'Build Notification Service'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
            fetchDepth: 1

          - task: Docker@2
            displayName: 'Login to ACR'
            inputs:
              command: login
              containerRegistry: 'citadelbuy-acr-connection'

          - task: Docker@2
            displayName: 'Build & Push Notification'
            inputs:
              command: buildAndPush
              repository: 'citadelbuy-notification'
              dockerfile: '$(Build.SourcesDirectory)/apps/services/notification/Dockerfile'
              containerRegistry: 'citadelbuy-acr-connection'
              tags: |
                $(tag)

      # Personalization Service
      - job: BuildPersonalization
        displayName: 'Build Personalization Service'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
            fetchDepth: 1

          - task: Docker@2
            displayName: 'Login to ACR'
            inputs:
              command: login
              containerRegistry: 'citadelbuy-acr-connection'

          - task: Docker@2
            displayName: 'Build & Push Personalization'
            inputs:
              command: buildAndPush
              repository: 'citadelbuy-personalization'
              dockerfile: '$(Build.SourcesDirectory)/apps/services/personalization/Dockerfile'
              containerRegistry: 'citadelbuy-acr-connection'
              tags: |
                $(tag)

  # ==========================================
  # Stage 2: Deploy to Development
  # ==========================================
  - stage: DeployDev
    displayName: 'Deploy to Development'
    dependsOn: BuildServices
    condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/develop'), eq(variables['Build.SourceBranch'], 'refs/heads/main')))
    variables:
      - group: citadelbuy-dev
      - name: namespace
        value: 'citadelbuy-dev'
    jobs:
      - deployment: DeployServicesToDev
        displayName: 'Deploy All Services to Dev'
        pool:
          vmImage: 'ubuntu-latest'
        environment: 'citadelbuy-dev'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                # Deploy AI Agents
                - task: KubernetesManifest@0
                  displayName: 'Deploy AI Agents'
                  inputs:
                    action: 'deploy'
                    kubernetesServiceConnection: 'citadelbuy-aks-dev'
                    namespace: '$(namespace)'
                    manifests: |
                      $(Build.SourcesDirectory)/infrastructure/kubernetes/apps/services/ai-agents/deployment.yaml
                      $(Build.SourcesDirectory)/infrastructure/kubernetes/apps/services/ai-agents/service.yaml
                    containers: '$(containerRegistry)/citadelbuy-ai-agents:$(tag)'

                # Deploy Inventory
                - task: KubernetesManifest@0
                  displayName: 'Deploy Inventory'
                  inputs:
                    action: 'deploy'
                    kubernetesServiceConnection: 'citadelbuy-aks-dev'
                    namespace: '$(namespace)'
                    manifests: |
                      $(Build.SourcesDirectory)/infrastructure/kubernetes/apps/services/inventory/deployment.yaml
                      $(Build.SourcesDirectory)/infrastructure/kubernetes/apps/services/inventory/service.yaml
                    containers: '$(containerRegistry)/citadelbuy-inventory:$(tag)'

                # Deploy Media
                - task: KubernetesManifest@0
                  displayName: 'Deploy Media'
                  inputs:
                    action: 'deploy'
                    kubernetesServiceConnection: 'citadelbuy-aks-dev'
                    namespace: '$(namespace)'
                    manifests: |
                      $(Build.SourcesDirectory)/infrastructure/kubernetes/apps/services/media/deployment.yaml
                      $(Build.SourcesDirectory)/infrastructure/kubernetes/apps/services/media/service.yaml
                    containers: '$(containerRegistry)/citadelbuy-media:$(tag)'

                # Deploy Notification
                - task: KubernetesManifest@0
                  displayName: 'Deploy Notification'
                  inputs:
                    action: 'deploy'
                    kubernetesServiceConnection: 'citadelbuy-aks-dev'
                    namespace: '$(namespace)'
                    manifests: |
                      $(Build.SourcesDirectory)/infrastructure/kubernetes/apps/services/notification/deployment.yaml
                      $(Build.SourcesDirectory)/infrastructure/kubernetes/apps/services/notification/service.yaml
                    containers: '$(containerRegistry)/citadelbuy-notification:$(tag)'

                # Deploy Personalization
                - task: KubernetesManifest@0
                  displayName: 'Deploy Personalization'
                  inputs:
                    action: 'deploy'
                    kubernetesServiceConnection: 'citadelbuy-aks-dev'
                    namespace: '$(namespace)'
                    manifests: |
                      $(Build.SourcesDirectory)/infrastructure/kubernetes/apps/services/personalization/deployment.yaml
                      $(Build.SourcesDirectory)/infrastructure/kubernetes/apps/services/personalization/service.yaml
                    containers: '$(containerRegistry)/citadelbuy-personalization:$(tag)'

      - job: SmokeTestDev
        displayName: 'Smoke Test Services - Dev'
        dependsOn: DeployServicesToDev
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              echo "Testing Python services on Dev..."

              # Test AI Agents
              curl -f https://ai-agents-dev.citadelbuy.com/health || echo "AI Agents health check failed"

              # Test other services
              services=(
                "inventory-dev.citadelbuy.com"
                "media-dev.citadelbuy.com"
                "notification-dev.citadelbuy.com"
                "personalization-dev.citadelbuy.com"
              )

              for service in "${services[@]}"; do
                response=$(curl -s -o /dev/null -w "%{http_code}" https://$service/health)
                if [ $response -eq 200 ]; then
                  echo "✓ $service is healthy"
                else
                  echo "✗ $service health check failed: $response"
                fi
              done
            displayName: 'Service Health Checks'

  # ==========================================
  # Stage 3: Deploy to Staging
  # ==========================================
  - stage: DeployStaging
    displayName: 'Deploy to Staging'
    dependsOn: DeployDev
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    variables:
      - group: citadelbuy-staging
      - name: namespace
        value: 'citadelbuy-staging'
    jobs:
      - deployment: DeployServicesToStaging
        displayName: 'Deploy All Services to Staging'
        pool:
          vmImage: 'ubuntu-latest'
        environment: 'citadelbuy-staging'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: KubernetesManifest@0
                  displayName: 'Deploy AI Agents'
                  inputs:
                    action: 'deploy'
                    kubernetesServiceConnection: 'citadelbuy-aks-staging'
                    namespace: '$(namespace)'
                    manifests: |
                      $(Build.SourcesDirectory)/infrastructure/kubernetes/apps/services/ai-agents/deployment.yaml
                      $(Build.SourcesDirectory)/infrastructure/kubernetes/apps/services/ai-agents/service.yaml
                    containers: '$(containerRegistry)/citadelbuy-ai-agents:$(tag)'

                - task: KubernetesManifest@0
                  displayName: 'Deploy Inventory'
                  inputs:
                    action: 'deploy'
                    kubernetesServiceConnection: 'citadelbuy-aks-staging'
                    namespace: '$(namespace)'
                    manifests: |
                      $(Build.SourcesDirectory)/infrastructure/kubernetes/apps/services/inventory/deployment.yaml
                      $(Build.SourcesDirectory)/infrastructure/kubernetes/apps/services/inventory/service.yaml
                    containers: '$(containerRegistry)/citadelbuy-inventory:$(tag)'

                - task: KubernetesManifest@0
                  displayName: 'Deploy Media'
                  inputs:
                    action: 'deploy'
                    kubernetesServiceConnection: 'citadelbuy-aks-staging'
                    namespace: '$(namespace)'
                    manifests: |
                      $(Build.SourcesDirectory)/infrastructure/kubernetes/apps/services/media/deployment.yaml
                      $(Build.SourcesDirectory)/infrastructure/kubernetes/apps/services/media/service.yaml
                    containers: '$(containerRegistry)/citadelbuy-media:$(tag)'

                - task: KubernetesManifest@0
                  displayName: 'Deploy Notification'
                  inputs:
                    action: 'deploy'
                    kubernetesServiceConnection: 'citadelbuy-aks-staging'
                    namespace: '$(namespace)'
                    manifests: |
                      $(Build.SourcesDirectory)/infrastructure/kubernetes/apps/services/notification/deployment.yaml
                      $(Build.SourcesDirectory)/infrastructure/kubernetes/apps/services/notification/service.yaml
                    containers: '$(containerRegistry)/citadelbuy-notification:$(tag)'

                - task: KubernetesManifest@0
                  displayName: 'Deploy Personalization'
                  inputs:
                    action: 'deploy'
                    kubernetesServiceConnection: 'citadelbuy-aks-staging'
                    namespace: '$(namespace)'
                    manifests: |
                      $(Build.SourcesDirectory)/infrastructure/kubernetes/apps/services/personalization/deployment.yaml
                      $(Build.SourcesDirectory)/infrastructure/kubernetes/apps/services/personalization/service.yaml
                    containers: '$(containerRegistry)/citadelbuy-personalization:$(tag)'

  # ==========================================
  # Stage 4: Deploy to Production
  # ==========================================
  - stage: DeployProduction
    displayName: 'Deploy to Production'
    dependsOn: DeployStaging
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    variables:
      - group: citadelbuy-production
      - name: namespace
        value: 'citadelbuy-prod'
    jobs:
      - deployment: DeployServicesToProd
        displayName: 'Deploy All Services to Production'
        pool:
          vmImage: 'ubuntu-latest'
        environment: 'citadelbuy-production'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: KubernetesManifest@0
                  displayName: 'Deploy AI Agents'
                  inputs:
                    action: 'deploy'
                    kubernetesServiceConnection: 'citadelbuy-aks-production'
                    namespace: '$(namespace)'
                    strategy: 'canary'
                    percentage: '25'
                    manifests: |
                      $(Build.SourcesDirectory)/infrastructure/kubernetes/apps/services/ai-agents/deployment.yaml
                      $(Build.SourcesDirectory)/infrastructure/kubernetes/apps/services/ai-agents/service.yaml
                    containers: '$(containerRegistry)/citadelbuy-ai-agents:$(tag)'

                - task: KubernetesManifest@0
                  displayName: 'Deploy Inventory'
                  inputs:
                    action: 'deploy'
                    kubernetesServiceConnection: 'citadelbuy-aks-production'
                    namespace: '$(namespace)'
                    strategy: 'canary'
                    percentage: '25'
                    manifests: |
                      $(Build.SourcesDirectory)/infrastructure/kubernetes/apps/services/inventory/deployment.yaml
                      $(Build.SourcesDirectory)/infrastructure/kubernetes/apps/services/inventory/service.yaml
                    containers: '$(containerRegistry)/citadelbuy-inventory:$(tag)'

                - task: KubernetesManifest@0
                  displayName: 'Deploy Media'
                  inputs:
                    action: 'deploy'
                    kubernetesServiceConnection: 'citadelbuy-aks-production'
                    namespace: '$(namespace)'
                    strategy: 'canary'
                    percentage: '25'
                    manifests: |
                      $(Build.SourcesDirectory)/infrastructure/kubernetes/apps/services/media/deployment.yaml
                      $(Build.SourcesDirectory)/infrastructure/kubernetes/apps/services/media/service.yaml
                    containers: '$(containerRegistry)/citadelbuy-media:$(tag)'

                - task: KubernetesManifest@0
                  displayName: 'Deploy Notification'
                  inputs:
                    action: 'deploy'
                    kubernetesServiceConnection: 'citadelbuy-aks-production'
                    namespace: '$(namespace)'
                    strategy: 'canary'
                    percentage: '25'
                    manifests: |
                      $(Build.SourcesDirectory)/infrastructure/kubernetes/apps/services/notification/deployment.yaml
                      $(Build.SourcesDirectory)/infrastructure/kubernetes/apps/services/notification/service.yaml
                    containers: '$(containerRegistry)/citadelbuy-notification:$(tag)'

                - task: KubernetesManifest@0
                  displayName: 'Deploy Personalization'
                  inputs:
                    action: 'deploy'
                    kubernetesServiceConnection: 'citadelbuy-aks-production'
                    namespace: '$(namespace)'
                    strategy: 'canary'
                    percentage: '25'
                    manifests: |
                      $(Build.SourcesDirectory)/infrastructure/kubernetes/apps/services/personalization/deployment.yaml
                      $(Build.SourcesDirectory)/infrastructure/kubernetes/apps/services/personalization/service.yaml
                    containers: '$(containerRegistry)/citadelbuy-personalization:$(tag)'

      - job: SmokeTestProduction
        displayName: 'Smoke Test - Production'
        dependsOn: DeployServicesToProd
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              echo "Running production smoke tests for services..."

              services=(
                "ai-agents.citadelbuy.com"
                "inventory.citadelbuy.com"
                "media.citadelbuy.com"
                "notification.citadelbuy.com"
                "personalization.citadelbuy.com"
              )

              for service in "${services[@]}"; do
                response=$(curl -s -o /dev/null -w "%{http_code}" https://$service/health)
                if [ $response -eq 200 ]; then
                  echo "✓ $service is healthy"
                else
                  echo "✗ $service failed: $response"
                  exit 1
                fi
              done

              echo "✓ All services are healthy"
            displayName: 'Production Health Checks'

      - job: PromoteCanary
        displayName: 'Promote All Services to 100%'
        dependsOn: SmokeTestProduction
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: KubernetesManifest@0
            displayName: 'Promote All Services'
            inputs:
              action: 'promote'
              kubernetesServiceConnection: 'citadelbuy-aks-production'
              namespace: '$(namespace)'
              strategy: 'canary'
