# ==========================================
# Broxiva - Web Frontend Continuous Deployment
# Deploys Next.js Web App to Azure Kubernetes Service
# Environments: dev, staging, production
# ==========================================
#
# NOTE: Production deployments require approval.
# Configure approvals in Azure DevOps: Project Settings > Environments > broxiva-production

trigger:
  branches:
    include:
      - main
      - master
      - develop
  paths:
    include:
      - 'apps/web/**'
      - 'packages/**'
      - '.azuredevops/pipelines/cd-web.yml'

pr: none

variables:
  - group: broxiva-common
  - group: broxiva-acr
  - name: dockerfilePath
    value: '$(Build.SourcesDirectory)/apps/web/Dockerfile.production'
  - name: imageRepository
    value: 'broxiva-web'
  - name: containerRegistry
    value: 'broxivaprod.azurecr.io'
  - name: tag
    value: '$(Build.BuildNumber)'

stages:
  # ==========================================
  # Stage 1: Build & Push Docker Image
  # ==========================================
  - stage: Build
    displayName: 'Build Docker Image'
    jobs:
      - job: BuildImage
        displayName: 'Build & Push to ACR'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
            fetchDepth: 1

          - task: Docker@2
            displayName: 'Login to ACR'
            inputs:
              command: login
              containerRegistry: 'broxiva-acr-connection'

          # Build Next.js with build args
          - task: Docker@2
            displayName: 'Build and Push Web Image'
            inputs:
              command: buildAndPush
              repository: $(imageRepository)
              dockerfile: $(dockerfilePath)
              containerRegistry: 'broxiva-acr-connection'
              tags: |
                $(tag)
                $(Build.SourceBranchName)
              arguments: |
                --build-arg NEXT_PUBLIC_API_URL=$(NEXT_PUBLIC_API_URL)
                --build-arg NEXT_PUBLIC_WS_URL=$(NEXT_PUBLIC_WS_URL)
                --build-arg NEXT_PUBLIC_AI_SERVICE_URL=$(NEXT_PUBLIC_AI_SERVICE_URL)
                --build-arg NEXT_PUBLIC_APP_NAME="Broxiva"
                --build-arg NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=$(STRIPE_PUBLISHABLE_KEY)
                --build-arg NEXT_PUBLIC_ENABLE_AI_FEATURES=true
                --build-arg NEXT_PUBLIC_SENTRY_DSN=$(SENTRY_DSN)

          # Scan for vulnerabilities
          - script: |
              docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
                aquasec/trivy image --severity HIGH,CRITICAL \
                $(containerRegistry)/$(imageRepository):$(tag)
            displayName: 'Scan Image with Trivy'
            continueOnError: true

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Build Info'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'web-build-info'

  # ==========================================
  # Stage 2: Deploy to Development
  # ==========================================
  - stage: DeployDev
    displayName: 'Deploy to Development'
    dependsOn: Build
    condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/develop'), eq(variables['Build.SourceBranch'], 'refs/heads/main')))
    variables:
      - group: broxiva-dev
      - name: environment
        value: 'dev'
      - name: namespace
        value: 'broxiva-dev'
      - name: appUrl
        value: 'https://dev.broxiva.com'
    jobs:
      - deployment: DeployToDevAKS
        displayName: 'Deploy to Dev AKS'
        pool:
          vmImage: 'ubuntu-latest'
        environment: 'broxiva-dev'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: qetza.replacetokens.replacetokens-task.replacetokens@5
                  displayName: 'Replace tokens in k8s manifests'
                  inputs:
                    rootDirectory: '$(Build.SourcesDirectory)/infrastructure/kubernetes'
                    targetFiles: |
                      apps/web/*.yaml
                      apps/web/*.yml
                    encoding: 'auto'
                    tokenPattern: 'default'

                - task: KubernetesManifest@0
                  displayName: 'Deploy Web to AKS Dev'
                  inputs:
                    action: 'deploy'
                    kubernetesServiceConnection: 'broxiva-aks-dev'
                    namespace: '$(namespace)'
                    manifests: |
                      $(Build.SourcesDirectory)/infrastructure/kubernetes/apps/web/deployment.yaml
                      $(Build.SourcesDirectory)/infrastructure/kubernetes/apps/web/service.yaml
                      $(Build.SourcesDirectory)/infrastructure/kubernetes/apps/web/ingress.yaml
                    containers: '$(containerRegistry)/$(imageRepository):$(tag)'

                # Wait for deployment to stabilize
                - task: Kubernetes@1
                  displayName: 'Wait for Rollout'
                  inputs:
                    connectionType: 'Kubernetes Service Connection'
                    kubernetesServiceEndpoint: 'broxiva-aks-dev'
                    namespace: '$(namespace)'
                    command: 'rollout'
                    arguments: 'status deployment/broxiva-web'

      - job: SmokeTestDev
        displayName: 'Smoke Tests - Dev'
        dependsOn: DeployToDevAKS
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              echo "Running smoke tests against Dev..."

              # Homepage check
              response=$(curl -s -o /dev/null -w "%{http_code}" https://dev.broxiva.com)
              if [ $response -eq 200 ]; then
                echo "✓ Homepage accessible"
              else
                echo "✗ Homepage failed: $response"
                exit 1
              fi

              # Check critical pages
              pages=(
                "/products"
                "/api/health"
              )

              for page in "${pages[@]}"; do
                response=$(curl -s -o /dev/null -w "%{http_code}" https://dev.broxiva.com$page)
                if [ $response -eq 200 ] || [ $response -eq 401 ]; then
                  echo "✓ $page is accessible"
                else
                  echo "✗ $page failed: $response"
                  exit 1
                fi
              done
            displayName: 'Run Smoke Tests'

          # Lighthouse performance check
          - task: NodeTool@0
            displayName: 'Install Node.js'
            inputs:
              versionSpec: '20.x'

          - script: |
              npm install -g @lhci/cli@0.12.x
              lhci healthcheck --fatal || true
            displayName: 'Lighthouse Performance Check'
            continueOnError: true

  # ==========================================
  # Stage 3: Deploy to Staging
  # ==========================================
  - stage: DeployStaging
    displayName: 'Deploy to Staging'
    dependsOn: DeployDev
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    variables:
      - group: broxiva-staging
      - name: environment
        value: 'staging'
      - name: namespace
        value: 'broxiva-staging'
      - name: appUrl
        value: 'https://staging.broxiva.com'
    jobs:
      - deployment: DeployToStagingAKS
        displayName: 'Deploy to Staging AKS'
        pool:
          vmImage: 'ubuntu-latest'
        environment: 'broxiva-staging'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: qetza.replacetokens.replacetokens-task.replacetokens@5
                  displayName: 'Replace tokens in k8s manifests'
                  inputs:
                    rootDirectory: '$(Build.SourcesDirectory)/infrastructure/kubernetes'
                    targetFiles: 'apps/web/*.yaml'
                    encoding: 'auto'
                    tokenPattern: 'default'

                - task: KubernetesManifest@0
                  displayName: 'Deploy Web to AKS Staging'
                  inputs:
                    action: 'deploy'
                    kubernetesServiceConnection: 'broxiva-aks-staging'
                    namespace: '$(namespace)'
                    manifests: |
                      $(Build.SourcesDirectory)/infrastructure/kubernetes/apps/web/deployment.yaml
                      $(Build.SourcesDirectory)/infrastructure/kubernetes/apps/web/service.yaml
                      $(Build.SourcesDirectory)/infrastructure/kubernetes/apps/web/ingress.yaml
                    containers: '$(containerRegistry)/$(imageRepository):$(tag)'

                - task: Kubernetes@1
                  displayName: 'Wait for Rollout'
                  inputs:
                    connectionType: 'Kubernetes Service Connection'
                    kubernetesServiceEndpoint: 'broxiva-aks-staging'
                    namespace: '$(namespace)'
                    command: 'rollout'
                    arguments: 'status deployment/broxiva-web'

      - job: E2ETestStaging
        displayName: 'E2E Tests - Staging'
        dependsOn: DeployToStagingAKS
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self

          - task: NodeTool@0
            displayName: 'Install Node.js'
            inputs:
              versionSpec: '20.x'

          - script: |
              npm install -g pnpm@10.23.0
              pnpm install
            displayName: 'Install Dependencies'

          - script: |
              cd apps/web
              npx playwright install --with-deps
              BASE_URL=https://staging.broxiva.com pnpm run test:e2e
            displayName: 'Run Playwright E2E Tests'
            env:
              CI: true

          - task: PublishTestResults@2
            displayName: 'Publish E2E Test Results'
            condition: always()
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: '**/playwright-results.xml'
              failTaskOnFailedTests: true

  # ==========================================
  # Stage 4: Deploy to Production
  # ==========================================
  - stage: DeployProduction
    displayName: 'Deploy to Production'
    dependsOn: DeployStaging
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    variables:
      - group: broxiva-production
      - name: environment
        value: 'production'
      - name: namespace
        value: 'broxiva-prod'
      - name: appUrl
        value: 'https://broxiva.com'
    jobs:
      - deployment: DeployToProdAKS
        displayName: 'Deploy to Production AKS'
        pool:
          vmImage: 'ubuntu-latest'
        environment: 'broxiva-production'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: qetza.replacetokens.replacetokens-task.replacetokens@5
                  displayName: 'Replace tokens in k8s manifests'
                  inputs:
                    rootDirectory: '$(Build.SourcesDirectory)/infrastructure/kubernetes'
                    targetFiles: 'apps/web/*.yaml'
                    encoding: 'auto'
                    tokenPattern: 'default'

                # Canary deployment
                - task: KubernetesManifest@0
                  displayName: 'Deploy Web to Production (Canary)'
                  inputs:
                    action: 'deploy'
                    kubernetesServiceConnection: 'broxiva-aks-production'
                    namespace: '$(namespace)'
                    strategy: 'canary'
                    percentage: '25'
                    manifests: |
                      $(Build.SourcesDirectory)/infrastructure/kubernetes/apps/web/deployment.yaml
                      $(Build.SourcesDirectory)/infrastructure/kubernetes/apps/web/service.yaml
                      $(Build.SourcesDirectory)/infrastructure/kubernetes/apps/web/ingress.yaml
                    containers: '$(containerRegistry)/$(imageRepository):$(tag)'

      - job: SmokeTestProduction
        displayName: 'Smoke Tests - Production'
        dependsOn: DeployToProdAKS
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              echo "Running production smoke tests..."

              # Critical pages
              pages=(
                "/"
                "/products"
                "/api/health"
                "/about"
              )

              for page in "${pages[@]}"; do
                response=$(curl -s -o /dev/null -w "%{http_code}" https://broxiva.com$page)
                if [ $response -eq 200 ] || [ $response -eq 401 ]; then
                  echo "✓ $page is accessible"
                else
                  echo "✗ $page failed: $response"
                  exit 1
                fi
              done

              echo "✓ All production smoke tests passed"
            displayName: 'Run Production Smoke Tests'

      - job: PromoteCanary
        displayName: 'Promote Canary to 100%'
        dependsOn: SmokeTestProduction
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: KubernetesManifest@0
            displayName: 'Promote to 100% traffic'
            inputs:
              action: 'promote'
              kubernetesServiceConnection: 'broxiva-aks-production'
              namespace: '$(namespace)'
              strategy: 'canary'
              manifests: |
                $(Build.SourcesDirectory)/infrastructure/kubernetes/apps/web/deployment.yaml

          # Purge CDN cache
          - task: AzureCLI@2
            displayName: 'Purge CDN Cache'
            inputs:
              azureSubscription: 'broxiva-azure-connection'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Purging CDN cache for new deployment..."
                # Add CDN purge commands here

          # Send notification
          - script: |
              echo "Web v$(tag) successfully deployed to production"
              echo "URL: https://broxiva.com"
            displayName: 'Deployment Complete'
