# ==========================================
# Broxiva - Main CI Pipeline
# Continuous Integration for Pull Requests
# Triggers on PR to main/master branches
# ==========================================

trigger: none  # Only trigger on PR, not on push

pr:
  branches:
    include:
      - main
      - master
      - develop
  paths:
    exclude:
      - '**.md'
      - 'docs/**'
      - '.gitignore'

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: broxiva-ci-variables
  - name: NODE_VERSION
    value: '20.x'
  - name: PNPM_VERSION
    value: '10.23.0'
  - name: PNPM_CACHE_FOLDER
    value: $(Pipeline.Workspace)/.pnpm-store

stages:
  # ==========================================
  # Stage 1: Code Quality & Security
  # ==========================================
  - stage: CodeQuality
    displayName: 'Code Quality & Security'
    jobs:
      - job: Lint
        displayName: 'Lint & Type Check'
        timeoutInMinutes: 15
        steps:
          - checkout: self
            fetchDepth: 1  # Shallow clone for faster checkout

          - task: NodeTool@0
            displayName: 'Install Node.js'
            inputs:
              versionSpec: $(NODE_VERSION)

          - script: |
              npm install -g pnpm@$(PNPM_VERSION)
              pnpm config set store-dir $(PNPM_CACHE_FOLDER)
            displayName: 'Setup pnpm'

          # Cache pnpm dependencies
          - task: Cache@2
            displayName: 'Cache pnpm dependencies'
            inputs:
              key: 'pnpm | "$(Agent.OS)" | pnpm-lock.yaml'
              path: $(PNPM_CACHE_FOLDER)
              restoreKeys: |
                pnpm | "$(Agent.OS)"

          - script: pnpm install --frozen-lockfile
            displayName: 'Install Dependencies'

          - script: pnpm run lint
            displayName: 'Run ESLint'
            continueOnError: false

          - script: pnpm run type-check
            displayName: 'Run TypeScript Type Check'
            continueOnError: false

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Lint Results'
            condition: always()
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'lint-results'

      - job: Security
        displayName: 'Security Scanning'
        timeoutInMinutes: 10
        steps:
          - checkout: self
            fetchDepth: 1

          - task: NodeTool@0
            displayName: 'Install Node.js'
            inputs:
              versionSpec: $(NODE_VERSION)

          - script: |
              npm install -g pnpm@$(PNPM_VERSION)
              pnpm config set store-dir $(PNPM_CACHE_FOLDER)
            displayName: 'Setup pnpm'

          - task: Cache@2
            displayName: 'Cache pnpm dependencies'
            inputs:
              key: 'pnpm | "$(Agent.OS)" | pnpm-lock.yaml'
              path: $(PNPM_CACHE_FOLDER)

          - script: pnpm install --frozen-lockfile
            displayName: 'Install Dependencies'

          - script: pnpm audit --audit-level=high
            displayName: 'Run pnpm Audit'
            continueOnError: true

          - script: |
              pnpm list --depth=0 --json > dependencies.json
              cat dependencies.json
            displayName: 'Generate Dependency List'

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Security Scan Results'
            inputs:
              PathtoPublish: 'dependencies.json'
              ArtifactName: 'security-scan'

  # ==========================================
  # Stage 2: Build & Test
  # ==========================================
  - stage: BuildAndTest
    displayName: 'Build & Test'
    dependsOn: CodeQuality
    jobs:
      # API Tests
      - job: TestAPI
        displayName: 'Test NestJS API'
        timeoutInMinutes: 30
        steps:
          - checkout: self
            fetchDepth: 1

          - task: NodeTool@0
            displayName: 'Install Node.js'
            inputs:
              versionSpec: $(NODE_VERSION)

          - script: |
              npm install -g pnpm@$(PNPM_VERSION)
              pnpm config set store-dir $(PNPM_CACHE_FOLDER)
            displayName: 'Setup pnpm'

          - task: Cache@2
            displayName: 'Cache pnpm dependencies'
            inputs:
              key: 'pnpm | "$(Agent.OS)" | pnpm-lock.yaml'
              path: $(PNPM_CACHE_FOLDER)

          - script: pnpm install --frozen-lockfile
            displayName: 'Install Dependencies'

          - script: |
              cd apps/api
              pnpm run test:cov
            displayName: 'Run API Tests with Coverage'
            env:
              NODE_ENV: test
              DATABASE_URL: postgresql://test:test@localhost:5432/testdb

          - task: PublishTestResults@2
            displayName: 'Publish API Test Results'
            condition: always()
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: '**/junit.xml'
              searchFolder: '$(System.DefaultWorkingDirectory)/apps/api'
              mergeTestResults: true
              failTaskOnFailedTests: true
              testRunTitle: 'API Tests'

          - task: PublishCodeCoverageResults@1
            displayName: 'Publish API Code Coverage'
            condition: always()
            inputs:
              codeCoverageTool: 'Cobertura'
              summaryFileLocation: '$(System.DefaultWorkingDirectory)/apps/api/coverage/cobertura-coverage.xml'
              reportDirectory: '$(System.DefaultWorkingDirectory)/apps/api/coverage'

      # Web Frontend Tests
      - job: TestWeb
        displayName: 'Test Next.js Web'
        timeoutInMinutes: 20
        steps:
          - checkout: self
            fetchDepth: 1

          - task: NodeTool@0
            displayName: 'Install Node.js'
            inputs:
              versionSpec: $(NODE_VERSION)

          - script: |
              npm install -g pnpm@$(PNPM_VERSION)
              pnpm config set store-dir $(PNPM_CACHE_FOLDER)
            displayName: 'Setup pnpm'

          - task: Cache@2
            displayName: 'Cache pnpm dependencies'
            inputs:
              key: 'pnpm | "$(Agent.OS)" | pnpm-lock.yaml'
              path: $(PNPM_CACHE_FOLDER)

          - script: pnpm install --frozen-lockfile
            displayName: 'Install Dependencies'

          - script: |
              cd apps/web
              pnpm run test
            displayName: 'Run Web Unit Tests'
            env:
              NODE_ENV: test

          - task: PublishTestResults@2
            displayName: 'Publish Web Test Results'
            condition: always()
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: '**/junit.xml'
              searchFolder: '$(System.DefaultWorkingDirectory)/apps/web'
              mergeTestResults: true
              failTaskOnFailedTests: true
              testRunTitle: 'Web Tests'

      # Build All Apps
      - job: BuildAll
        displayName: 'Build All Applications'
        timeoutInMinutes: 30
        steps:
          - checkout: self
            fetchDepth: 1

          - task: NodeTool@0
            displayName: 'Install Node.js'
            inputs:
              versionSpec: $(NODE_VERSION)

          - script: |
              npm install -g pnpm@$(PNPM_VERSION)
              pnpm config set store-dir $(PNPM_CACHE_FOLDER)
            displayName: 'Setup pnpm'

          - task: Cache@2
            displayName: 'Cache pnpm dependencies'
            inputs:
              key: 'pnpm | "$(Agent.OS)" | pnpm-lock.yaml'
              path: $(PNPM_CACHE_FOLDER)

          - script: pnpm install --frozen-lockfile
            displayName: 'Install Dependencies'

          # Build packages first (dependencies)
          - script: pnpm run build:packages
            displayName: 'Build Shared Packages'

          # Build API
          - script: |
              cd apps/api
              npx prisma generate
              pnpm run build
            displayName: 'Build NestJS API'
            env:
              NODE_ENV: production

          # Build Web
          - script: |
              cd apps/web
              pnpm run build
            displayName: 'Build Next.js Web'
            env:
              NODE_ENV: production
              NEXT_TELEMETRY_DISABLED: 1

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Build Artifacts'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'build-output'

  # ==========================================
  # Stage 3: Report Results
  # ==========================================
  - stage: Report
    displayName: 'Generate Reports'
    dependsOn: BuildAndTest
    condition: always()
    jobs:
      - job: GenerateReport
        displayName: 'Generate Build Report'
        steps:
          - checkout: none

          - script: |
              echo "================================================"
              echo "Broxiva CI Pipeline Summary"
              echo "================================================"
              echo "Build ID: $(Build.BuildId)"
              echo "Build Number: $(Build.BuildNumber)"
              echo "Source Branch: $(Build.SourceBranch)"
              echo "Commit: $(Build.SourceVersion)"
              echo "Triggered By: $(Build.RequestedFor)"
              echo "================================================"
            displayName: 'Display Build Summary'

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Final Report'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'ci-report'
