# ==========================================
# CitadelBuy - Infrastructure Pipeline
# Terraform-based infrastructure provisioning
# Environments: dev, staging, production
# ==========================================

trigger:
  branches:
    include:
      - main
      - master
  paths:
    include:
      - 'infrastructure/terraform/**'
      - '.azuredevops/pipelines/infrastructure.yml'

pr:
  branches:
    include:
      - main
      - master
  paths:
    include:
      - 'infrastructure/terraform/**'

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: citadelbuy-common
  - group: citadelbuy-terraform
  - name: terraformVersion
    value: '1.6.0'
  - name: terraformWorkingDirectory
    value: '$(Build.SourcesDirectory)/infrastructure/terraform'

stages:
  # ==========================================
  # Stage 1: Validate Terraform Configuration
  # ==========================================
  - stage: Validate
    displayName: 'Validate Terraform'
    jobs:
      - job: TerraformValidate
        displayName: 'Terraform Validate & Format Check'
        steps:
          - checkout: self
            fetchDepth: 1

          - task: TerraformInstaller@1
            displayName: 'Install Terraform'
            inputs:
              terraformVersion: $(terraformVersion)

          - script: |
              cd $(terraformWorkingDirectory)
              terraform fmt -check -recursive
            displayName: 'Terraform Format Check'
            continueOnError: true

          - script: |
              cd $(terraformWorkingDirectory)/environments/dev
              terraform init -backend=false
              terraform validate
            displayName: 'Validate Dev Environment'

          - script: |
              cd $(terraformWorkingDirectory)/environments/staging
              terraform init -backend=false
              terraform validate
            displayName: 'Validate Staging Environment'

          - script: |
              cd $(terraformWorkingDirectory)/environments/prod
              terraform init -backend=false
              terraform validate
            displayName: 'Validate Production Environment'

      - job: SecurityScan
        displayName: 'Security Scan with Checkov'
        steps:
          - checkout: self
            fetchDepth: 1

          - task: UsePythonVersion@0
            displayName: 'Install Python'
            inputs:
              versionSpec: '3.11'

          - script: |
              pip install checkov
              checkov -d $(terraformWorkingDirectory) \
                --framework terraform \
                --output cli \
                --output junitxml \
                --output-file-path $(Build.ArtifactStagingDirectory)
            displayName: 'Run Checkov Security Scan'
            continueOnError: true

          - task: PublishTestResults@2
            displayName: 'Publish Security Scan Results'
            condition: always()
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: '$(Build.ArtifactStagingDirectory)/**/*.xml'
              failTaskOnFailedTests: false

  # ==========================================
  # Stage 2: Plan Development Environment
  # ==========================================
  - stage: PlanDev
    displayName: 'Plan - Development'
    dependsOn: Validate
    condition: succeeded()
    variables:
      - group: citadelbuy-dev
      - name: environment
        value: 'dev'
    jobs:
      - job: TerraformPlanDev
        displayName: 'Terraform Plan for Dev'
        steps:
          - checkout: self
            fetchDepth: 1

          - task: TerraformInstaller@1
            displayName: 'Install Terraform'
            inputs:
              terraformVersion: $(terraformVersion)

          - task: AzureCLI@2
            displayName: 'Terraform Init & Plan - Dev'
            inputs:
              azureSubscription: 'citadelbuy-azure-connection'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                cd $(terraformWorkingDirectory)/environments/dev

                # Initialize Terraform with Azure backend
                terraform init \
                  -backend-config="resource_group_name=$(TF_BACKEND_RG)" \
                  -backend-config="storage_account_name=$(TF_BACKEND_SA)" \
                  -backend-config="container_name=$(TF_BACKEND_CONTAINER)" \
                  -backend-config="key=dev.tfstate"

                # Create Terraform plan
                terraform plan \
                  -var="environment=dev" \
                  -var="azure_subscription_id=$(ARM_SUBSCRIPTION_ID)" \
                  -var="azure_tenant_id=$(ARM_TENANT_ID)" \
                  -out=tfplan \
                  -detailed-exitcode || exit_code=$?

                # Save exit code (0 = no changes, 1 = error, 2 = changes)
                if [ $exit_code -eq 1 ]; then
                  echo "Terraform plan failed"
                  exit 1
                elif [ $exit_code -eq 2 ]; then
                  echo "Terraform plan has changes"
                  echo "##vso[task.setvariable variable=HasChanges]true"
                fi

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Dev Plan'
            inputs:
              PathtoPublish: '$(terraformWorkingDirectory)/environments/dev/tfplan'
              ArtifactName: 'terraform-plan-dev'

  # ==========================================
  # Stage 3: Apply Development Environment
  # ==========================================
  - stage: ApplyDev
    displayName: 'Apply - Development'
    dependsOn: PlanDev
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    variables:
      - group: citadelbuy-dev
      - name: environment
        value: 'dev'
    jobs:
      - deployment: TerraformApplyDev
        displayName: 'Terraform Apply for Dev'
        pool:
          vmImage: 'ubuntu-latest'
        environment: 'citadelbuy-dev-infra'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: TerraformInstaller@1
                  displayName: 'Install Terraform'
                  inputs:
                    terraformVersion: $(terraformVersion)

                - task: DownloadBuildArtifacts@0
                  displayName: 'Download Plan'
                  inputs:
                    buildType: 'current'
                    downloadType: 'single'
                    artifactName: 'terraform-plan-dev'
                    downloadPath: '$(System.ArtifactsDirectory)'

                - task: AzureCLI@2
                  displayName: 'Terraform Apply - Dev'
                  inputs:
                    azureSubscription: 'citadelbuy-azure-connection'
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      cd $(terraformWorkingDirectory)/environments/dev

                      terraform init \
                        -backend-config="resource_group_name=$(TF_BACKEND_RG)" \
                        -backend-config="storage_account_name=$(TF_BACKEND_SA)" \
                        -backend-config="container_name=$(TF_BACKEND_CONTAINER)" \
                        -backend-config="key=dev.tfstate"

                      terraform apply \
                        -auto-approve \
                        $(System.ArtifactsDirectory)/terraform-plan-dev/tfplan

                - script: |
                    echo "Development infrastructure deployed successfully"
                  displayName: 'Deployment Summary'

  # ==========================================
  # Stage 4: Plan Staging Environment
  # ==========================================
  - stage: PlanStaging
    displayName: 'Plan - Staging'
    dependsOn: ApplyDev
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    variables:
      - group: citadelbuy-staging
      - name: environment
        value: 'staging'
    jobs:
      - job: TerraformPlanStaging
        displayName: 'Terraform Plan for Staging'
        steps:
          - checkout: self
            fetchDepth: 1

          - task: TerraformInstaller@1
            displayName: 'Install Terraform'
            inputs:
              terraformVersion: $(terraformVersion)

          - task: AzureCLI@2
            displayName: 'Terraform Init & Plan - Staging'
            inputs:
              azureSubscription: 'citadelbuy-azure-connection'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                cd $(terraformWorkingDirectory)/environments/staging

                terraform init \
                  -backend-config="resource_group_name=$(TF_BACKEND_RG)" \
                  -backend-config="storage_account_name=$(TF_BACKEND_SA)" \
                  -backend-config="container_name=$(TF_BACKEND_CONTAINER)" \
                  -backend-config="key=staging.tfstate"

                terraform plan \
                  -var="environment=staging" \
                  -var="azure_subscription_id=$(ARM_SUBSCRIPTION_ID)" \
                  -var="azure_tenant_id=$(ARM_TENANT_ID)" \
                  -out=tfplan

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Staging Plan'
            inputs:
              PathtoPublish: '$(terraformWorkingDirectory)/environments/staging/tfplan'
              ArtifactName: 'terraform-plan-staging'

  # ==========================================
  # Stage 5: Apply Staging Environment
  # ==========================================
  - stage: ApplyStaging
    displayName: 'Apply - Staging'
    dependsOn: PlanStaging
    condition: succeeded()
    variables:
      - group: citadelbuy-staging
      - name: environment
        value: 'staging'
    jobs:
      - deployment: TerraformApplyStaging
        displayName: 'Terraform Apply for Staging'
        pool:
          vmImage: 'ubuntu-latest'
        environment: 'citadelbuy-staging-infra'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: TerraformInstaller@1
                  displayName: 'Install Terraform'
                  inputs:
                    terraformVersion: $(terraformVersion)

                - task: DownloadBuildArtifacts@0
                  displayName: 'Download Plan'
                  inputs:
                    buildType: 'current'
                    downloadType: 'single'
                    artifactName: 'terraform-plan-staging'
                    downloadPath: '$(System.ArtifactsDirectory)'

                - task: AzureCLI@2
                  displayName: 'Terraform Apply - Staging'
                  inputs:
                    azureSubscription: 'citadelbuy-azure-connection'
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      cd $(terraformWorkingDirectory)/environments/staging

                      terraform init \
                        -backend-config="resource_group_name=$(TF_BACKEND_RG)" \
                        -backend-config="storage_account_name=$(TF_BACKEND_SA)" \
                        -backend-config="container_name=$(TF_BACKEND_CONTAINER)" \
                        -backend-config="key=staging.tfstate"

                      terraform apply \
                        -auto-approve \
                        $(System.ArtifactsDirectory)/terraform-plan-staging/tfplan

  # ==========================================
  # Stage 6: Plan Production Environment
  # ==========================================
  - stage: PlanProduction
    displayName: 'Plan - Production'
    dependsOn: ApplyStaging
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    variables:
      - group: citadelbuy-production
      - name: environment
        value: 'production'
    jobs:
      - job: TerraformPlanProduction
        displayName: 'Terraform Plan for Production'
        steps:
          - checkout: self
            fetchDepth: 1

          - task: TerraformInstaller@1
            displayName: 'Install Terraform'
            inputs:
              terraformVersion: $(terraformVersion)

          - task: AzureCLI@2
            displayName: 'Terraform Init & Plan - Production'
            inputs:
              azureSubscription: 'citadelbuy-azure-connection'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                cd $(terraformWorkingDirectory)/environments/prod

                terraform init \
                  -backend-config="resource_group_name=$(TF_BACKEND_RG)" \
                  -backend-config="storage_account_name=$(TF_BACKEND_SA)" \
                  -backend-config="container_name=$(TF_BACKEND_CONTAINER)" \
                  -backend-config="key=prod.tfstate"

                terraform plan \
                  -var="environment=production" \
                  -var="azure_subscription_id=$(ARM_SUBSCRIPTION_ID)" \
                  -var="azure_tenant_id=$(ARM_TENANT_ID)" \
                  -out=tfplan

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Production Plan'
            inputs:
              PathtoPublish: '$(terraformWorkingDirectory)/environments/prod/tfplan'
              ArtifactName: 'terraform-plan-prod'

          - script: |
              cd $(terraformWorkingDirectory)/environments/prod
              terraform show -no-color tfplan > plan-summary.txt
              cat plan-summary.txt
            displayName: 'Show Plan Summary'

  # ==========================================
  # Stage 7: Apply Production Environment
  # REQUIRES MANUAL APPROVAL
  # ==========================================
  - stage: ApplyProduction
    displayName: 'Apply - Production'
    dependsOn: PlanProduction
    condition: succeeded()
    variables:
      - group: citadelbuy-production
      - name: environment
        value: 'production'
    jobs:
      - deployment: TerraformApplyProduction
        displayName: 'Terraform Apply for Production'
        pool:
          vmImage: 'ubuntu-latest'
        environment: 'citadelbuy-production-infra'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: TerraformInstaller@1
                  displayName: 'Install Terraform'
                  inputs:
                    terraformVersion: $(terraformVersion)

                - task: DownloadBuildArtifacts@0
                  displayName: 'Download Plan'
                  inputs:
                    buildType: 'current'
                    downloadType: 'single'
                    artifactName: 'terraform-plan-prod'
                    downloadPath: '$(System.ArtifactsDirectory)'

                # Backup current state before applying
                - task: AzureCLI@2
                  displayName: 'Backup Terraform State'
                  inputs:
                    azureSubscription: 'citadelbuy-azure-connection'
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      timestamp=$(date +%Y%m%d-%H%M%S)
                      az storage blob copy start \
                        --account-name $(TF_BACKEND_SA) \
                        --destination-container tfstate-backups \
                        --destination-blob "prod-${timestamp}.tfstate" \
                        --source-container $(TF_BACKEND_CONTAINER) \
                        --source-blob prod.tfstate

                - task: AzureCLI@2
                  displayName: 'Terraform Apply - Production'
                  inputs:
                    azureSubscription: 'citadelbuy-azure-connection'
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      cd $(terraformWorkingDirectory)/environments/prod

                      terraform init \
                        -backend-config="resource_group_name=$(TF_BACKEND_RG)" \
                        -backend-config="storage_account_name=$(TF_BACKEND_SA)" \
                        -backend-config="container_name=$(TF_BACKEND_CONTAINER)" \
                        -backend-config="key=prod.tfstate"

                      terraform apply \
                        -auto-approve \
                        $(System.ArtifactsDirectory)/terraform-plan-prod/tfplan

                - script: |
                    echo "================================================"
                    echo "Production infrastructure successfully deployed"
                    echo "Environment: Production"
                    echo "Build: $(Build.BuildNumber)"
                    echo "================================================"
                  displayName: 'Deployment Summary'

                # Verify infrastructure
                - task: AzureCLI@2
                  displayName: 'Verify Infrastructure'
                  inputs:
                    azureSubscription: 'citadelbuy-azure-connection'
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      echo "Verifying production infrastructure..."
                      # Add verification commands here
