# ==================================================================================================
# CitadelBuy - Unified Master Pipeline
# ==================================================================================================
#
# This is the MAIN entry point for ALL CI/CD operations in Azure DevOps
#
# Organization: citadelcloudmanagement
# Project: CitadelBuy
# ACR: citadelbuyacr.azurecr.io
# Service Connection: CitadelBuyAzure
#
# Pipeline orchestrates:
# - Code validation (linting, type checking, code quality)
# - Testing (unit, integration, E2E)
# - Security scanning (Trivy, dependency audit, SAST)
# - Docker image builds and registry push
# - Multi-environment deployments (dev, staging, production)
# - Infrastructure as Code (Terraform)
# - Post-deployment verification
# ==================================================================================================

# ==================================================================================================
# TRIGGER CONFIGURATION
# ==================================================================================================
trigger:
  branches:
    include:
      - main
      - develop
      - feature/*
      - release/*
      - hotfix/*
  paths:
    exclude:
      - '**/*.md'
      - 'docs/**'
      - 'documentation/**'
      - '.github/**'
      - '*.txt'
      - 'LICENSE'
      - '.gitignore'

# Pull Request Triggers
pr:
  branches:
    include:
      - main
      - develop
  paths:
    exclude:
      - '**/*.md'
      - 'docs/**'
      - 'documentation/**'
      - '.github/**'

# ==================================================================================================
# PIPELINE PARAMETERS
# ==================================================================================================
parameters:
  # Testing Configuration
  - name: skipTests
    displayName: 'Skip all tests (not recommended)'
    type: boolean
    default: false

  # Deployment Environment Selection
  - name: deployEnvironment
    displayName: 'Target Deployment Environment'
    type: string
    default: 'none'
    values:
      - none
      - dev
      - staging
      - prod

  # Microservices Build Selection
  - name: buildMicroservices
    displayName: 'Build specific microservices (comma-separated, or "all")'
    type: string
    default: 'all'
    # Examples: 'all', 'api,web', 'api,worker,notification'

  # End-to-End Testing
  - name: runE2E
    displayName: 'Run E2E tests on staging'
    type: boolean
    default: false

  # Terraform Operations
  - name: terraformAction
    displayName: 'Terraform Action'
    type: string
    default: 'none'
    values:
      - none
      - plan
      - apply
      - destroy

  # Security Scanning
  - name: skipSecurityScan
    displayName: 'Skip security scanning (not recommended)'
    type: boolean
    default: false

  # Docker Registry Push
  - name: pushToRegistry
    displayName: 'Push Docker images to ACR'
    type: boolean
    default: true

# ==================================================================================================
# GLOBAL VARIABLES
# ==================================================================================================
variables:
  # Import common variables
  - template: variables/common.yml

  # Build metadata
  - name: BuildTimestamp
    value: $[format('{0:yyyyMMddHHmmss}', pipeline.startTime)]

  - name: ShortSHA
    value: $[substring(variables['Build.SourceVersion'], 0, 7)]

  - name: BranchName
    value: $[replace(replace(variables['Build.SourceBranchName'], '/', '-'), '_', '-')]

  # Environment-specific variables
  - name: IsMainBranch
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

  - name: IsDevelopBranch
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/develop')]

  - name: IsFeatureBranch
    value: $[startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/')]

  - name: IsReleaseBranch
    value: $[startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')]

  - name: IsHotfixBranch
    value: $[startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix/')]

  - name: IsPR
    value: $[eq(variables['Build.Reason'], 'PullRequest')]

  # Deployment flags
  - name: ShouldDeployDev
    value: $[or(eq(variables.IsDevelopBranch, true), eq(variables.IsFeatureBranch, true))]

  - name: ShouldDeployStaging
    value: $[or(eq(variables.IsDevelopBranch, true), eq(variables.IsReleaseBranch, true))]

  - name: ShouldDeployProduction
    value: $[or(eq(variables.IsMainBranch, true), eq(variables.IsHotfixBranch, true))]

# ==================================================================================================
# AGENT POOL CONFIGURATION
# ==================================================================================================
pool:
  vmImage: ubuntu-latest

# ==================================================================================================
# PIPELINE STAGES
# ==================================================================================================
stages:

  # ================================================================================================
  # STAGE 1: VALIDATE
  # Code quality, linting, formatting, and type checking
  # ================================================================================================
  - stage: Validate
    displayName: 'Validate - Code Quality & Standards'
    condition: succeeded()
    jobs:
      - template: templates/stages/validate.yml
        parameters:
          skipLinting: false
          skipTypeCheck: false
          skipFormatCheck: false

  # ================================================================================================
  # STAGE 2: TEST
  # Unit tests, integration tests with Postgres and Redis services
  # ================================================================================================
  - stage: Test
    displayName: 'Test - Unit & Integration Tests'
    dependsOn: Validate
    condition: and(succeeded(), eq('${{ parameters.skipTests }}', false))
    jobs:
      - template: templates/stages/test.yml
        parameters:
          runUnitTests: true
          runIntegrationTests: true
          enableCodeCoverage: true
          publishCoverageReports: true
          services:
            postgres:
              enabled: true
              version: '16-alpine'
            redis:
              enabled: true
              version: '7-alpine'

  # ================================================================================================
  # STAGE 3: SECURITY SCAN
  # Trivy vulnerability scanning, dependency audits, SAST analysis
  # ================================================================================================
  - stage: SecurityScan
    displayName: 'Security - Vulnerability & Dependency Scan'
    dependsOn: Validate
    condition: and(succeeded(), eq('${{ parameters.skipSecurityScan }}', false))
    jobs:
      - template: templates/stages/security-scan.yml
        parameters:
          runTrivy: true
          runDependencyAudit: true
          runSAST: true
          failOnHighSeverity: false
          failOnCriticalSeverity: true

  # ================================================================================================
  # STAGE 4: BUILD
  # Build Node.js applications, compile TypeScript, prepare artifacts
  # ================================================================================================
  - stage: Build
    displayName: 'Build - Compile Applications'
    dependsOn:
      - Validate
      - Test
    condition: and(succeeded(), or(eq(variables.IsMainBranch, true), eq(variables.IsDevelopBranch, true), eq('${{ parameters.deployEnvironment }}', 'dev'), eq('${{ parameters.deployEnvironment }}', 'staging'), eq('${{ parameters.deployEnvironment }}', 'prod')))
    jobs:
      - template: templates/stages/build.yml
        parameters:
          buildConfiguration: Release
          publishArtifacts: true
          microservices: '${{ parameters.buildMicroservices }}'

  # ================================================================================================
  # STAGE 5: DOCKER BUILD
  # Build Docker images and push to Azure Container Registry
  # ================================================================================================
  - stage: DockerBuild
    displayName: 'Docker - Build & Push to ACR'
    dependsOn:
      - Build
      - SecurityScan
    condition: and(succeeded(), eq('${{ parameters.pushToRegistry }}', true))
    jobs:
      - template: templates/stages/docker-build.yml
        parameters:
          registry: citadelbuyacr.azurecr.io
          serviceConnection: CitadelBuyAzure
          acrServiceConnection: CitadelBuyACR
          buildContext: $(System.DefaultWorkingDirectory)
          microservices: '${{ parameters.buildMicroservices }}'
          tags:
            - $(Build.BuildId)
            - $(ShortSHA)
            - $(BranchName)
            - latest
          scanImages: true
          pushToRegistry: true

  # ================================================================================================
  # STAGE 6: DEPLOY DEV
  # Deploy to Development AKS cluster (auto-deploy on develop/feature branches)
  # ================================================================================================
  - stage: DeployDev
    displayName: 'Deploy - Development Environment'
    dependsOn: DockerBuild
    condition: |
      and(
        succeeded(),
        or(
          and(eq(variables.ShouldDeployDev, true), eq('${{ parameters.deployEnvironment }}', 'none')),
          eq('${{ parameters.deployEnvironment }}', 'dev')
        ),
        ne(variables.IsPR, true)
      )
    jobs:
      - template: templates/stages/deploy-dev.yml
        parameters:
          environment: dev
          serviceConnection: CitadelBuyAzure
          aksResourceGroup: citadelbuy-dev-rg
          aksClusterName: citadelbuy-dev-aks
          namespace: citadelbuy-dev
          imageTag: $(ShortSHA)
          runMigrations: true
          healthCheckEnabled: true

  # ================================================================================================
  # STAGE 7: DEPLOY STAGING
  # Deploy to Staging AKS cluster (requires dev deployment success)
  # ================================================================================================
  - stage: DeployStaging
    displayName: 'Deploy - Staging Environment'
    dependsOn:
      - DockerBuild
      - DeployDev
    condition: |
      and(
        in(dependencies.DockerBuild.result, 'Succeeded'),
        or(
          and(eq(variables.ShouldDeployStaging, true), eq('${{ parameters.deployEnvironment }}', 'none')),
          eq('${{ parameters.deployEnvironment }}', 'staging')
        ),
        ne(variables.IsPR, true)
      )
    jobs:
      - template: templates/stages/deploy-staging.yml
        parameters:
          environment: staging
          serviceConnection: CitadelBuyAzure
          aksResourceGroup: citadelbuy-staging-rg
          aksClusterName: citadelbuy-staging-aks
          namespace: citadelbuy-staging
          imageTag: $(ShortSHA)
          runMigrations: true
          healthCheckEnabled: true
          requireApproval: false

  # ================================================================================================
  # STAGE 8: E2E TESTS
  # End-to-End testing on Staging environment with Playwright
  # ================================================================================================
  - stage: E2ETests
    displayName: 'Test - End-to-End on Staging'
    dependsOn: DeployStaging
    condition: |
      and(
        succeeded(),
        or(
          eq('${{ parameters.runE2E }}', true),
          and(eq(variables.IsDevelopBranch, true), eq('${{ parameters.runE2E }}', false))
        )
      )
    jobs:
      - template: templates/stages/e2e-tests.yml
        parameters:
          environment: staging
          baseUrl: https://staging.citadelbuy.com
          browser: chromium
          parallelWorkers: 4
          retries: 2
          publishReports: true

  # ================================================================================================
  # STAGE 9: DEPLOY PRODUCTION
  # Deploy to Production AKS cluster (requires manual approval)
  # Blue-Green deployment strategy with traffic switching
  # ================================================================================================
  - stage: DeployProduction
    displayName: 'Deploy - Production Environment'
    dependsOn:
      - DockerBuild
      - DeployStaging
      - E2ETests
    condition: |
      and(
        in(dependencies.DockerBuild.result, 'Succeeded'),
        or(
          eq(dependencies.DeployStaging.result, 'Succeeded'),
          eq(dependencies.DeployStaging.result, 'Skipped')
        ),
        or(
          eq(dependencies.E2ETests.result, 'Succeeded'),
          eq(dependencies.E2ETests.result, 'Skipped')
        ),
        or(
          and(eq(variables.ShouldDeployProduction, true), eq('${{ parameters.deployEnvironment }}', 'none')),
          eq('${{ parameters.deployEnvironment }}', 'prod')
        ),
        ne(variables.IsPR, true)
      )
    jobs:
      - template: templates/stages/deploy-production.yml
        parameters:
          environment: production
          serviceConnection: CitadelBuyAzure
          aksResourceGroup: citadelbuy-prod-rg
          aksClusterName: citadelbuy-prod-aks
          namespace: citadelbuy-prod
          imageTag: $(ShortSHA)
          deploymentStrategy: blueGreen
          runMigrations: true
          requireApproval: true
          healthCheckEnabled: true
          smokeTestsEnabled: true
          canaryPercentage: 0
          approvalTimeout: 1440 # 24 hours

  # ================================================================================================
  # STAGE 10: POST-DEPLOY VERIFICATION
  # Health checks, smoke tests, performance validation
  # ================================================================================================
  - stage: PostDeployVerify
    displayName: 'Verify - Post-Deployment Health Checks'
    dependsOn: DeployProduction
    condition: succeeded()
    jobs:
      - template: templates/stages/post-deploy-verify.yml
        parameters:
          environment: production
          endpoints:
            - name: API Health
              url: https://api.citadelbuy.com/health
              expectedStatus: 200
            - name: Web Application
              url: https://citadelbuy.com
              expectedStatus: 200
            - name: Admin Portal
              url: https://admin.citadelbuy.com
              expectedStatus: 200
          performanceTests: true
          metricsValidation: true
          rollbackOnFailure: true

  # ================================================================================================
  # STAGE 11: TERRAFORM
  # Infrastructure as Code - Parallel stage independent of deployment pipeline
  # ================================================================================================
  - stage: Terraform
    displayName: 'Infrastructure - Terraform (IaC)'
    dependsOn: []
    condition: |
      and(
        succeeded(),
        ne('${{ parameters.terraformAction }}', 'none'),
        or(
          eq(variables.IsMainBranch, true),
          eq(variables.IsDevelopBranch, true),
          eq(variables.IsPR, true)
        )
      )
    jobs:
      - template: templates/stages/terraform.yml
        parameters:
          action: '${{ parameters.terraformAction }}'
          serviceConnection: CitadelBuyAzure
          environment: ${{ if eq(variables.IsMainBranch, true) }}
            production
          ${{ elseif eq(variables.IsDevelopBranch, true) }}
            staging
          ${{ else }}
            dev
          workingDirectory: infrastructure/terraform/environments
          backendResourceGroup: citadelbuy-tfstate-rg
          backendStorageAccount: citadelbuytfstate
          backendContainer: tfstate
          requireApproval: ${{ eq(parameters.terraformAction, 'apply') }}

# ==================================================================================================
# POST-PIPELINE NOTIFICATIONS
# ==================================================================================================
# Note: Notification tasks should be added to individual stage templates
# Common notification channels:
# - Slack: $(SLACK_WEBHOOK_URL)
# - Microsoft Teams: $(TEAMS_WEBHOOK_URL)
# - Email: Azure DevOps built-in notifications
# ==================================================================================================
