# ==========================================
# Broxiva - Coordinated Release Pipeline
# Orchestrates deployment of all components
# Includes rollback capabilities and approval gates
# ==========================================
#
# NOTE: Production deployments require approval.
# Configure approvals in Azure DevOps: Project Settings > Environments > broxiva-production

trigger: none  # Manual trigger only

pr: none

parameters:
  - name: deployEnvironment
    displayName: 'Target Environment'
    type: string
    default: 'staging'
    values:
      - dev
      - staging
      - production

  - name: deployAPI
    displayName: 'Deploy API'
    type: boolean
    default: true

  - name: deployWeb
    displayName: 'Deploy Web Frontend'
    type: boolean
    default: true

  - name: deployServices
    displayName: 'Deploy Python Services'
    type: boolean
    default: true

  - name: runMigrations
    displayName: 'Run Database Migrations'
    type: boolean
    default: true

  - name: version
    displayName: 'Release Version (e.g., v2.1.0)'
    type: string
    default: 'auto'

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: broxiva-common
  - group: broxiva-${{ parameters.deployEnvironment }}
  - name: containerRegistry
    value: 'broxivaprod.azurecr.io'
  - name: releaseVersion
    ${{ if eq(parameters.version, 'auto') }}:
      value: '$(Build.BuildNumber)'
    ${{ else }}:
      value: ${{ parameters.version }}

stages:
  # ==========================================
  # Stage 1: Pre-Deployment Validation
  # ==========================================
  - stage: PreDeployment
    displayName: 'Pre-Deployment Validation'
    jobs:
      - job: ValidationChecks
        displayName: 'Validation & Health Checks'
        steps:
          - checkout: self
            fetchDepth: 1

          - script: |
              echo "================================================"
              echo "Broxiva Release Pipeline"
              echo "================================================"
              echo "Release Version: $(releaseVersion)"
              echo "Target Environment: ${{ parameters.deployEnvironment }}"
              echo "Deploy API: ${{ parameters.deployAPI }}"
              echo "Deploy Web: ${{ parameters.deployWeb }}"
              echo "Deploy Services: ${{ parameters.deployServices }}"
              echo "Run Migrations: ${{ parameters.runMigrations }}"
              echo "================================================"
            displayName: 'Display Release Information'

          # Validate current environment health
          - script: |
              echo "Checking current environment health..."

              if [ "${{ parameters.deployEnvironment }}" = "production" ]; then
                base_url="https://broxiva.com"
              elif [ "${{ parameters.deployEnvironment }}" = "staging" ]; then
                base_url="https://staging.broxiva.com"
              else
                base_url="https://dev.broxiva.com"
              fi

              # Check API health
              api_status=$(curl -s -o /dev/null -w "%{http_code}" ${base_url}/api/health || echo "0")
              echo "API Health Status: $api_status"

              # Check Web health
              web_status=$(curl -s -o /dev/null -w "%{http_code}" ${base_url} || echo "0")
              echo "Web Health Status: $web_status"

              if [ "$api_status" != "200" ] && [ "${{ parameters.deployEnvironment }}" = "production" ]; then
                echo "WARNING: Production API is not healthy before deployment"
              fi
            displayName: 'Pre-Deployment Health Check'
            continueOnError: true

          # Check for active incidents
          - task: AzureCLI@2
            displayName: 'Check for Active Incidents'
            inputs:
              azureSubscription: 'broxiva-azure-connection'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Checking for active incidents..."
                # Add logic to check monitoring/alerting systems
                # Exit 1 if critical incidents are active

          # Backup current state
          - ${{ if eq(parameters.deployEnvironment, 'production') }}:
            - task: AzureCLI@2
              displayName: 'Create Production Backup'
              inputs:
                azureSubscription: 'broxiva-azure-connection'
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  echo "Creating production database backup..."
                  timestamp=$(date +%Y%m%d-%H%M%S)
                  echo "Backup timestamp: $timestamp"
                  # Add backup commands here

  # ==========================================
  # Stage 2: Deploy Database Migrations
  # ==========================================
  - stage: DeployMigrations
    displayName: 'Deploy Database Migrations'
    dependsOn: PreDeployment
    condition: and(succeeded(), eq('${{ parameters.runMigrations }}', 'true'))
    jobs:
      - deployment: RunMigrations
        displayName: 'Run Database Migrations'
        pool:
          vmImage: 'ubuntu-latest'
        environment: broxiva-${{ parameters.deployEnvironment }}
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: Kubernetes@1
                  displayName: 'Run Prisma Migrations'
                  inputs:
                    connectionType: 'Kubernetes Service Connection'
                    kubernetesServiceEndpoint: 'broxiva-aks-${{ parameters.deployEnvironment }}'
                    namespace: 'broxiva-${{ parameters.deployEnvironment }}'
                    command: 'exec'
                    arguments: 'deployment/broxiva-api -- npx prisma migrate deploy'

                - script: |
                    echo "Database migrations completed successfully"
                  displayName: 'Migration Summary'

  # ==========================================
  # Stage 3: Deploy Backend API
  # ==========================================
  - stage: DeployAPI
    displayName: 'Deploy API'
    dependsOn:
      - PreDeployment
      - DeployMigrations
    condition: |
      and(
        in(dependencies.PreDeployment.result, 'Succeeded'),
        in(dependencies.DeployMigrations.result, 'Succeeded', 'Skipped'),
        eq('${{ parameters.deployAPI }}', 'true')
      )
    jobs:
      - deployment: DeployAPIService
        displayName: 'Deploy NestJS API'
        pool:
          vmImage: 'ubuntu-latest'
        environment: broxiva-${{ parameters.deployEnvironment }}
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: KubernetesManifest@0
                  displayName: 'Deploy API to AKS'
                  inputs:
                    action: 'deploy'
                    kubernetesServiceConnection: 'broxiva-aks-${{ parameters.deployEnvironment }}'
                    namespace: 'broxiva-${{ parameters.deployEnvironment }}'
                    ${{ if eq(parameters.deployEnvironment, 'production') }}:
                      strategy: 'canary'
                      percentage: '25'
                    manifests: |
                      $(Build.SourcesDirectory)/infrastructure/kubernetes/apps/api/deployment.yaml
                      $(Build.SourcesDirectory)/infrastructure/kubernetes/apps/api/service.yaml
                    containers: '$(containerRegistry)/broxiva-api:$(releaseVersion)'

                - task: Kubernetes@1
                  displayName: 'Wait for API Rollout'
                  inputs:
                    connectionType: 'Kubernetes Service Connection'
                    kubernetesServiceEndpoint: 'broxiva-aks-${{ parameters.deployEnvironment }}'
                    namespace: 'broxiva-${{ parameters.deployEnvironment }}'
                    command: 'rollout'
                    arguments: 'status deployment/broxiva-api --timeout=5m'

      - job: TestAPI
        displayName: 'Test API Deployment'
        dependsOn: DeployAPIService
        steps:
          - script: |
              if [ "${{ parameters.deployEnvironment }}" = "production" ]; then
                api_url="https://api.broxiva.com"
              elif [ "${{ parameters.deployEnvironment }}" = "staging" ]; then
                api_url="https://api-staging.broxiva.com"
              else
                api_url="https://api-dev.broxiva.com"
              fi

              echo "Testing API at: $api_url"

              # Health check
              response=$(curl -s -o /dev/null -w "%{http_code}" ${api_url}/api/health)
              if [ $response -eq 200 ]; then
                echo "✓ API health check passed"
              else
                echo "✗ API health check failed: $response"
                exit 1
              fi

              # Version check
              version=$(curl -s ${api_url}/api | jq -r '.version' || echo "unknown")
              echo "API Version: $version"

              # Critical endpoints
              endpoints=("/api/products" "/api/categories" "/api/auth/status")
              for endpoint in "${endpoints[@]}"; do
                status=$(curl -s -o /dev/null -w "%{http_code}" ${api_url}${endpoint})
                if [ $status -eq 200 ] || [ $status -eq 401 ]; then
                  echo "✓ $endpoint is accessible"
                else
                  echo "✗ $endpoint failed: $status"
                  exit 1
                fi
              done

              echo "✓ All API tests passed"
            displayName: 'Run API Tests'

  # ==========================================
  # Stage 4: Deploy Web Frontend
  # ==========================================
  - stage: DeployWeb
    displayName: 'Deploy Web Frontend'
    dependsOn:
      - DeployAPI
    condition: |
      and(
        in(dependencies.DeployAPI.result, 'Succeeded', 'Skipped'),
        eq('${{ parameters.deployWeb }}', 'true')
      )
    jobs:
      - deployment: DeployWebApp
        displayName: 'Deploy Next.js Web'
        pool:
          vmImage: 'ubuntu-latest'
        environment: broxiva-${{ parameters.deployEnvironment }}
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: KubernetesManifest@0
                  displayName: 'Deploy Web to AKS'
                  inputs:
                    action: 'deploy'
                    kubernetesServiceConnection: 'broxiva-aks-${{ parameters.deployEnvironment }}'
                    namespace: 'broxiva-${{ parameters.deployEnvironment }}'
                    ${{ if eq(parameters.deployEnvironment, 'production') }}:
                      strategy: 'canary'
                      percentage: '25'
                    manifests: |
                      $(Build.SourcesDirectory)/infrastructure/kubernetes/apps/web/deployment.yaml
                      $(Build.SourcesDirectory)/infrastructure/kubernetes/apps/web/service.yaml
                      $(Build.SourcesDirectory)/infrastructure/kubernetes/apps/web/ingress.yaml
                    containers: '$(containerRegistry)/broxiva-web:$(releaseVersion)'

                - task: Kubernetes@1
                  displayName: 'Wait for Web Rollout'
                  inputs:
                    connectionType: 'Kubernetes Service Connection'
                    kubernetesServiceEndpoint: 'broxiva-aks-${{ parameters.deployEnvironment }}'
                    namespace: 'broxiva-${{ parameters.deployEnvironment }}'
                    command: 'rollout'
                    arguments: 'status deployment/broxiva-web --timeout=5m'

      - job: TestWeb
        displayName: 'Test Web Deployment'
        dependsOn: DeployWebApp
        steps:
          - script: |
              if [ "${{ parameters.deployEnvironment }}" = "production" ]; then
                web_url="https://broxiva.com"
              elif [ "${{ parameters.deployEnvironment }}" = "staging" ]; then
                web_url="https://staging.broxiva.com"
              else
                web_url="https://dev.broxiva.com"
              fi

              echo "Testing Web at: $web_url"

              # Homepage check
              response=$(curl -s -o /dev/null -w "%{http_code}" ${web_url})
              if [ $response -eq 200 ]; then
                echo "✓ Homepage is accessible"
              else
                echo "✗ Homepage failed: $response"
                exit 1
              fi

              # Critical pages
              pages=("/products" "/about" "/contact")
              for page in "${pages[@]}"; do
                status=$(curl -s -o /dev/null -w "%{http_code}" ${web_url}${page})
                if [ $status -eq 200 ]; then
                  echo "✓ $page is accessible"
                else
                  echo "✗ $page failed: $status"
                  exit 1
                fi
              done

              echo "✓ All web tests passed"
            displayName: 'Run Web Tests'

  # ==========================================
  # Stage 5: Deploy Python Services
  # ==========================================
  - stage: DeployServices
    displayName: 'Deploy Python Services'
    dependsOn:
      - DeployAPI
    condition: |
      and(
        in(dependencies.DeployAPI.result, 'Succeeded', 'Skipped'),
        eq('${{ parameters.deployServices }}', 'true')
      )
    jobs:
      - deployment: DeployPythonServices
        displayName: 'Deploy All Python Services'
        pool:
          vmImage: 'ubuntu-latest'
        environment: broxiva-${{ parameters.deployEnvironment }}
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                # Deploy all services
                - task: KubernetesManifest@0
                  displayName: 'Deploy AI Agents Service'
                  inputs:
                    action: 'deploy'
                    kubernetesServiceConnection: 'broxiva-aks-${{ parameters.deployEnvironment }}'
                    namespace: 'broxiva-${{ parameters.deployEnvironment }}'
                    manifests: |
                      $(Build.SourcesDirectory)/infrastructure/kubernetes/apps/services/ai-agents/deployment.yaml
                      $(Build.SourcesDirectory)/infrastructure/kubernetes/apps/services/ai-agents/service.yaml
                    containers: '$(containerRegistry)/broxiva-ai-agents:$(releaseVersion)'

                - task: KubernetesManifest@0
                  displayName: 'Deploy Inventory Service'
                  inputs:
                    action: 'deploy'
                    kubernetesServiceConnection: 'broxiva-aks-${{ parameters.deployEnvironment }}'
                    namespace: 'broxiva-${{ parameters.deployEnvironment }}'
                    manifests: |
                      $(Build.SourcesDirectory)/infrastructure/kubernetes/apps/services/inventory/deployment.yaml
                      $(Build.SourcesDirectory)/infrastructure/kubernetes/apps/services/inventory/service.yaml
                    containers: '$(containerRegistry)/broxiva-inventory:$(releaseVersion)'

                - task: KubernetesManifest@0
                  displayName: 'Deploy Media Service'
                  inputs:
                    action: 'deploy'
                    kubernetesServiceConnection: 'broxiva-aks-${{ parameters.deployEnvironment }}'
                    namespace: 'broxiva-${{ parameters.deployEnvironment }}'
                    manifests: |
                      $(Build.SourcesDirectory)/infrastructure/kubernetes/apps/services/media/deployment.yaml
                      $(Build.SourcesDirectory)/infrastructure/kubernetes/apps/services/media/service.yaml
                    containers: '$(containerRegistry)/broxiva-media:$(releaseVersion)'

  # ==========================================
  # Stage 6: Promote Canary (Production Only)
  # ==========================================
  - ${{ if eq(parameters.deployEnvironment, 'production') }}:
    - stage: PromoteCanary
      displayName: 'Promote Canary to 100%'
      dependsOn:
        - DeployAPI
        - DeployWeb
        - DeployServices
      condition: succeeded()
      jobs:
        - deployment: PromoteToFullTraffic
          displayName: 'Promote All Services'
          pool:
            vmImage: 'ubuntu-latest'
          environment: 'broxiva-production'
          strategy:
            runOnce:
              deploy:
                steps:
                  - checkout: self

                  - ${{ if eq(parameters.deployAPI, 'true') }}:
                    - task: KubernetesManifest@0
                      displayName: 'Promote API to 100%'
                      inputs:
                        action: 'promote'
                        kubernetesServiceConnection: 'broxiva-aks-production'
                        namespace: 'broxiva-prod'
                        strategy: 'canary'
                        manifests: '$(Build.SourcesDirectory)/infrastructure/kubernetes/apps/api/deployment.yaml'

                  - ${{ if eq(parameters.deployWeb, 'true') }}:
                    - task: KubernetesManifest@0
                      displayName: 'Promote Web to 100%'
                      inputs:
                        action: 'promote'
                        kubernetesServiceConnection: 'broxiva-aks-production'
                        namespace: 'broxiva-prod'
                        strategy: 'canary'
                        manifests: '$(Build.SourcesDirectory)/infrastructure/kubernetes/apps/web/deployment.yaml'

  # ==========================================
  # Stage 7: Post-Deployment Validation
  # ==========================================
  - stage: PostDeployment
    displayName: 'Post-Deployment Validation'
    dependsOn:
      - DeployAPI
      - DeployWeb
      - DeployServices
    condition: always()
    jobs:
      - job: FinalValidation
        displayName: 'Final Health & Smoke Tests'
        steps:
          - script: |
              echo "================================================"
              echo "Release $(releaseVersion) Deployment Summary"
              echo "Environment: ${{ parameters.deployEnvironment }}"
              echo "================================================"

              if [ "${{ parameters.deployEnvironment }}" = "production" ]; then
                base_url="https://broxiva.com"
              elif [ "${{ parameters.deployEnvironment }}" = "staging" ]; then
                base_url="https://staging.broxiva.com"
              else
                base_url="https://dev.broxiva.com"
              fi

              # Full system health check
              echo "Running full system health check..."

              api_health=$(curl -s -o /dev/null -w "%{http_code}" ${base_url}/api/health)
              web_health=$(curl -s -o /dev/null -w "%{http_code}" ${base_url})

              echo "API Health: $api_health"
              echo "Web Health: $web_health"

              if [ "$api_health" = "200" ] && [ "$web_health" = "200" ]; then
                echo "✓ All systems are healthy"
              else
                echo "✗ Some systems are not healthy"
                exit 1
              fi

              echo "================================================"
              echo "Deployment completed successfully!"
              echo "================================================"
            displayName: 'Final System Health Check'

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Deployment Report'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'release-report'
