# ==============================================================================
# AWS CodeBuild Build Specification
# Broxiva E-Commerce Platform - Node.js Services (API and Web)
# ==============================================================================
# This buildspec handles building and pushing Docker images for:
# - apps/api (NestJS Backend)
# - apps/web (Next.js Frontend)
# ==============================================================================

version: 0.2

env:
  variables:
    # Default environment settings
    NODE_ENV: "production"
    DOCKER_BUILDKIT: "1"
  parameter-store:
    # AWS Secrets Manager references (configure in AWS Console)
    DOCKER_USERNAME: "/broxiva/docker/username"
    DOCKER_PASSWORD: "/broxiva/docker/password"
  exported-variables:
    - IMAGE_TAG
    - API_IMAGE_URI
    - WEB_IMAGE_URI

phases:
  install:
    runtime-versions:
      nodejs: 20
      docker: latest
    commands:
      - echo "=== Installing Dependencies ==="
      - echo "Node.js version:" && node --version
      - echo "npm version:" && npm --version

      # Install pnpm globally
      - npm install -g pnpm@latest
      - echo "pnpm version:" && pnpm --version

      # Install AWS CLI v2 if not present
      - |
        if ! command -v aws &> /dev/null; then
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip -q awscliv2.zip
          ./aws/install --update
        fi
      - aws --version

  pre_build:
    commands:
      - echo "=== Pre-Build Phase ==="
      - echo "Build started on $(date)"

      # Set build variables
      - export COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-8)
      - export BUILD_DATE=$(date +%Y%m%d)
      - export IMAGE_TAG="${BUILD_DATE}-${COMMIT_HASH}"
      - echo "Image tag:" $IMAGE_TAG

      # Login to Amazon ECR
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

      # Define ECR repository URIs
      - export ECR_REGISTRY="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com"
      - export API_IMAGE_URI="$ECR_REGISTRY/broxiva/api:$IMAGE_TAG"
      - export WEB_IMAGE_URI="$ECR_REGISTRY/broxiva/web:$IMAGE_TAG"

      # Install project dependencies
      - echo "Installing project dependencies..."
      - cd $CODEBUILD_SRC_DIR/organization
      - pnpm install --frozen-lockfile

      # Run linting
      - echo "Running ESLint..."
      - pnpm run lint --if-present || echo "Lint completed with warnings"

      # Run type checking
      - echo "Running TypeScript type checking..."
      - pnpm run type-check --if-present || pnpm run typecheck --if-present || echo "Type check not configured"

  build:
    commands:
      - echo "=== Build Phase ==="
      - cd $CODEBUILD_SRC_DIR/organization

      # Run tests
      - echo "Running tests..."
      - pnpm run test --if-present || echo "No tests configured"

      # Build API Docker image
      - echo "Building API Docker image..."
      - cd $CODEBUILD_SRC_DIR/organization/apps/api
      - |
        docker build \
          --build-arg NODE_ENV=production \
          --build-arg BUILD_DATE=$BUILD_DATE \
          --build-arg COMMIT_HASH=$COMMIT_HASH \
          --cache-from $ECR_REGISTRY/broxiva/api:latest \
          -t $API_IMAGE_URI \
          -t $ECR_REGISTRY/broxiva/api:latest \
          -f Dockerfile.production .

      # Build Web Docker image
      - echo "Building Web Docker image..."
      - cd $CODEBUILD_SRC_DIR/organization/apps/web
      - |
        docker build \
          --build-arg NODE_ENV=production \
          --build-arg BUILD_DATE=$BUILD_DATE \
          --build-arg COMMIT_HASH=$COMMIT_HASH \
          --cache-from $ECR_REGISTRY/broxiva/web:latest \
          -t $WEB_IMAGE_URI \
          -t $ECR_REGISTRY/broxiva/web:latest \
          -f Dockerfile.production .

  post_build:
    commands:
      - echo "=== Post-Build Phase ==="
      - echo "Build completed on $(date)"

      # Push images to ECR
      - echo "Pushing API image to ECR..."
      - docker push $API_IMAGE_URI
      - docker push $ECR_REGISTRY/broxiva/api:latest

      - echo "Pushing Web image to ECR..."
      - docker push $WEB_IMAGE_URI
      - docker push $ECR_REGISTRY/broxiva/web:latest

      # Generate imagedefinitions.json for ECS deployment
      - echo "Generating image definitions for ECS..."
      - cd $CODEBUILD_SRC_DIR
      - |
        cat > imagedefinitions.json << EOF
        [
          {
            "name": "api",
            "imageUri": "$API_IMAGE_URI"
          },
          {
            "name": "web",
            "imageUri": "$WEB_IMAGE_URI"
          }
        ]
        EOF
      - cat imagedefinitions.json

      # Generate build artifacts summary
      - |
        cat > build-summary.json << EOF
        {
          "buildId": "$CODEBUILD_BUILD_ID",
          "buildNumber": "$CODEBUILD_BUILD_NUMBER",
          "sourceVersion": "$CODEBUILD_RESOLVED_SOURCE_VERSION",
          "imageTag": "$IMAGE_TAG",
          "images": {
            "api": "$API_IMAGE_URI",
            "web": "$WEB_IMAGE_URI"
          },
          "buildDate": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
        }
        EOF

artifacts:
  files:
    - imagedefinitions.json
    - build-summary.json
  discard-paths: yes

cache:
  paths:
    - '/root/.pnpm-store/**/*'
    - 'organization/node_modules/**/*'
    - '/root/.cache/docker/**/*'

reports:
  jest-reports:
    files:
      - 'organization/**/junit.xml'
      - 'organization/**/test-results.xml'
    file-format: JUNITXML
  coverage-reports:
    files:
      - 'organization/**/coverage/clover.xml'
    file-format: CLOVERXML
