-- Rollback migration: 20251118154530_sync_schema_phase30
-- This script reverses all changes made in migration.sql

-- Drop foreign keys (in reverse order of creation)
ALTER TABLE "_OrderGiftCards" DROP CONSTRAINT IF EXISTS "_OrderGiftCards_B_fkey";
ALTER TABLE "_OrderGiftCards" DROP CONSTRAINT IF EXISTS "_OrderGiftCards_A_fkey";
ALTER TABLE "store_credit_transactions" DROP CONSTRAINT IF EXISTS "store_credit_transactions_orderId_fkey";
ALTER TABLE "store_credit_transactions" DROP CONSTRAINT IF EXISTS "store_credit_transactions_storeCreditId_fkey";
ALTER TABLE "store_credits" DROP CONSTRAINT IF EXISTS "store_credits_userId_fkey";
ALTER TABLE "gift_card_transactions" DROP CONSTRAINT IF EXISTS "gift_card_transactions_userId_fkey";
ALTER TABLE "gift_card_transactions" DROP CONSTRAINT IF EXISTS "gift_card_transactions_orderId_fkey";
ALTER TABLE "gift_card_transactions" DROP CONSTRAINT IF EXISTS "gift_card_transactions_giftCardId_fkey";
ALTER TABLE "gift_cards" DROP CONSTRAINT IF EXISTS "gift_cards_orderId_fkey";
ALTER TABLE "gift_cards" DROP CONSTRAINT IF EXISTS "gift_cards_redeemedBy_fkey";
ALTER TABLE "gift_cards" DROP CONSTRAINT IF EXISTS "gift_cards_purchasedBy_fkey";
ALTER TABLE "deal_notifications" DROP CONSTRAINT IF EXISTS "deal_notifications_userId_fkey";
ALTER TABLE "deal_purchases" DROP CONSTRAINT IF EXISTS "deal_purchases_orderId_fkey";
ALTER TABLE "deal_purchases" DROP CONSTRAINT IF EXISTS "deal_purchases_userId_fkey";
ALTER TABLE "deal_purchases" DROP CONSTRAINT IF EXISTS "deal_purchases_dealId_fkey";
ALTER TABLE "deal_products" DROP CONSTRAINT IF EXISTS "deal_products_productId_fkey";
ALTER TABLE "deal_products" DROP CONSTRAINT IF EXISTS "deal_products_dealId_fkey";
ALTER TABLE "referrals" DROP CONSTRAINT IF EXISTS "referrals_refereeId_fkey";
ALTER TABLE "referrals" DROP CONSTRAINT IF EXISTS "referrals_referrerId_fkey";
ALTER TABLE "reward_redemptions" DROP CONSTRAINT IF EXISTS "reward_redemptions_orderId_fkey";
ALTER TABLE "reward_redemptions" DROP CONSTRAINT IF EXISTS "reward_redemptions_rewardId_fkey";
ALTER TABLE "reward_redemptions" DROP CONSTRAINT IF EXISTS "reward_redemptions_loyaltyId_fkey";
ALTER TABLE "point_transactions" DROP CONSTRAINT IF EXISTS "point_transactions_orderId_fkey";
ALTER TABLE "point_transactions" DROP CONSTRAINT IF EXISTS "point_transactions_loyaltyId_fkey";
ALTER TABLE "customer_loyalty" DROP CONSTRAINT IF EXISTS "customer_loyalty_userId_fkey";
ALTER TABLE "translations" DROP CONSTRAINT IF EXISTS "translations_languageCode_fkey";
ALTER TABLE "category_translations" DROP CONSTRAINT IF EXISTS "category_translations_languageCode_fkey";
ALTER TABLE "category_translations" DROP CONSTRAINT IF EXISTS "category_translations_categoryId_fkey";
ALTER TABLE "product_translations" DROP CONSTRAINT IF EXISTS "product_translations_languageCode_fkey";
ALTER TABLE "product_translations" DROP CONSTRAINT IF EXISTS "product_translations_productId_fkey";
ALTER TABLE "category_analytics" DROP CONSTRAINT IF EXISTS "category_analytics_categoryId_fkey";
ALTER TABLE "product_analytics" DROP CONSTRAINT IF EXISTS "product_analytics_productId_fkey";
ALTER TABLE "vendor_analytics" DROP CONSTRAINT IF EXISTS "vendor_analytics_vendorId_fkey";
ALTER TABLE "saved_searches" DROP CONSTRAINT IF EXISTS "saved_searches_userId_fkey";
ALTER TABLE "product_views" DROP CONSTRAINT IF EXISTS "product_views_userId_fkey";
ALTER TABLE "product_views" DROP CONSTRAINT IF EXISTS "product_views_productId_fkey";
ALTER TABLE "search_queries" DROP CONSTRAINT IF EXISTS "search_queries_userId_fkey";
ALTER TABLE "bnpl_installments" DROP CONSTRAINT IF EXISTS "bnpl_installments_paymentPlanId_fkey";
ALTER TABLE "bnpl_payment_plans" DROP CONSTRAINT IF EXISTS "bnpl_payment_plans_userId_fkey";
ALTER TABLE "bnpl_payment_plans" DROP CONSTRAINT IF EXISTS "bnpl_payment_plans_orderId_fkey";
ALTER TABLE "subscription_invoices" DROP CONSTRAINT IF EXISTS "subscription_invoices_subscriptionId_fkey";
ALTER TABLE "subscriptions" DROP CONSTRAINT IF EXISTS "subscriptions_planId_fkey";
ALTER TABLE "subscriptions" DROP CONSTRAINT IF EXISTS "subscriptions_userId_fkey";
ALTER TABLE "ad_clicks" DROP CONSTRAINT IF EXISTS "ad_clicks_adId_fkey";
ALTER TABLE "ad_impressions" DROP CONSTRAINT IF EXISTS "ad_impressions_adId_fkey";
ALTER TABLE "ad_keywords" DROP CONSTRAINT IF EXISTS "ad_keywords_adId_fkey";
ALTER TABLE "advertisements" DROP CONSTRAINT IF EXISTS "advertisements_productId_fkey";
ALTER TABLE "advertisements" DROP CONSTRAINT IF EXISTS "advertisements_vendorId_fkey";
ALTER TABLE "advertisements" DROP CONSTRAINT IF EXISTS "advertisements_campaignId_fkey";
ALTER TABLE "ad_campaigns" DROP CONSTRAINT IF EXISTS "ad_campaigns_vendorId_fkey";
ALTER TABLE "product_variants" DROP CONSTRAINT IF EXISTS "product_variants_productId_fkey";
ALTER TABLE "wishlist" DROP CONSTRAINT IF EXISTS "wishlist_productId_fkey";
ALTER TABLE "wishlist" DROP CONSTRAINT IF EXISTS "wishlist_userId_fkey";
ALTER TABLE "review_votes" DROP CONSTRAINT IF EXISTS "review_votes_reviewId_fkey";

-- Drop indexes (in reverse order)
DROP INDEX IF EXISTS "_OrderGiftCards_B_index";
DROP INDEX IF EXISTS "_OrderGiftCards_AB_unique";
DROP INDEX IF EXISTS "store_credit_transactions_expiresAt_idx";
DROP INDEX IF EXISTS "store_credit_transactions_createdAt_idx";
DROP INDEX IF EXISTS "store_credit_transactions_type_idx";
DROP INDEX IF EXISTS "store_credit_transactions_orderId_idx";
DROP INDEX IF EXISTS "store_credit_transactions_storeCreditId_idx";
DROP INDEX IF EXISTS "store_credits_userId_idx";
DROP INDEX IF EXISTS "store_credits_userId_key";
DROP INDEX IF EXISTS "gift_card_transactions_createdAt_idx";
DROP INDEX IF EXISTS "gift_card_transactions_type_idx";
DROP INDEX IF EXISTS "gift_card_transactions_userId_idx";
DROP INDEX IF EXISTS "gift_card_transactions_orderId_idx";
DROP INDEX IF EXISTS "gift_card_transactions_giftCardId_idx";
DROP INDEX IF EXISTS "gift_cards_expirationDate_idx";
DROP INDEX IF EXISTS "gift_cards_recipientEmail_idx";
DROP INDEX IF EXISTS "gift_cards_redeemedBy_idx";
DROP INDEX IF EXISTS "gift_cards_purchasedBy_idx";
DROP INDEX IF EXISTS "gift_cards_status_idx";
DROP INDEX IF EXISTS "gift_cards_code_idx";
DROP INDEX IF EXISTS "gift_cards_code_key";
DROP INDEX IF EXISTS "deal_analytics_dealId_key";
DROP INDEX IF EXISTS "deal_notifications_productId_idx";
DROP INDEX IF EXISTS "deal_notifications_dealId_idx";
DROP INDEX IF EXISTS "deal_notifications_userId_isActive_idx";
DROP INDEX IF EXISTS "deal_purchases_orderId_idx";
DROP INDEX IF EXISTS "deal_purchases_userId_idx";
DROP INDEX IF EXISTS "deal_purchases_dealId_idx";
DROP INDEX IF EXISTS "deal_products_dealId_productId_key";
DROP INDEX IF EXISTS "deal_products_productId_idx";
DROP INDEX IF EXISTS "deal_products_dealId_isActive_idx";
DROP INDEX IF EXISTS "deals_isFeatured_featuredOrder_idx";
DROP INDEX IF EXISTS "deals_type_idx";
DROP INDEX IF EXISTS "deals_status_startTime_endTime_idx";
DROP INDEX IF EXISTS "referrals_status_idx";
DROP INDEX IF EXISTS "referrals_refereeEmail_idx";
DROP INDEX IF EXISTS "referrals_refereeId_idx";
DROP INDEX IF EXISTS "referrals_referrerId_idx";
DROP INDEX IF EXISTS "reward_redemptions_orderId_idx";
DROP INDEX IF EXISTS "reward_redemptions_rewardId_idx";
DROP INDEX IF EXISTS "reward_redemptions_loyaltyId_idx";
DROP INDEX IF EXISTS "rewards_isActive_idx";
DROP INDEX IF EXISTS "rewards_type_idx";
DROP INDEX IF EXISTS "loyalty_tier_benefits_tier_key";
DROP INDEX IF EXISTS "point_transactions_expiresAt_idx";
DROP INDEX IF EXISTS "point_transactions_orderId_idx";
DROP INDEX IF EXISTS "point_transactions_loyaltyId_createdAt_idx";
DROP INDEX IF EXISTS "customer_loyalty_referralCode_idx";
DROP INDEX IF EXISTS "customer_loyalty_currentTier_idx";
DROP INDEX IF EXISTS "customer_loyalty_referralCode_key";
DROP INDEX IF EXISTS "customer_loyalty_userId_key";
DROP INDEX IF EXISTS "translations_languageCode_key_namespace_key";
DROP INDEX IF EXISTS "translations_key_idx";
DROP INDEX IF EXISTS "translations_languageCode_namespace_idx";
DROP INDEX IF EXISTS "category_translations_categoryId_languageCode_key";
DROP INDEX IF EXISTS "category_translations_slug_idx";
DROP INDEX IF EXISTS "category_translations_languageCode_idx";
DROP INDEX IF EXISTS "category_translations_categoryId_idx";
DROP INDEX IF EXISTS "product_translations_productId_languageCode_key";
DROP INDEX IF EXISTS "product_translations_slug_idx";
DROP INDEX IF EXISTS "product_translations_languageCode_idx";
DROP INDEX IF EXISTS "product_translations_productId_idx";
DROP INDEX IF EXISTS "languages_isDefault_isEnabled_idx";
DROP INDEX IF EXISTS "languages_code_idx";
DROP INDEX IF EXISTS "languages_code_key";
DROP INDEX IF EXISTS "traffic_analytics_period_date_key";
DROP INDEX IF EXISTS "traffic_analytics_date_idx";
DROP INDEX IF EXISTS "traffic_analytics_period_date_idx";
DROP INDEX IF EXISTS "revenue_analytics_period_date_key";
DROP INDEX IF EXISTS "revenue_analytics_date_idx";
DROP INDEX IF EXISTS "revenue_analytics_period_date_idx";
DROP INDEX IF EXISTS "category_analytics_categoryId_period_date_key";
DROP INDEX IF EXISTS "category_analytics_date_idx";
DROP INDEX IF EXISTS "category_analytics_categoryId_period_date_idx";
DROP INDEX IF EXISTS "product_analytics_productId_period_date_key";
DROP INDEX IF EXISTS "product_analytics_date_idx";
DROP INDEX IF EXISTS "product_analytics_productId_period_date_idx";
DROP INDEX IF EXISTS "vendor_analytics_vendorId_period_date_key";
DROP INDEX IF EXISTS "vendor_analytics_date_idx";
DROP INDEX IF EXISTS "vendor_analytics_vendorId_period_date_idx";
DROP INDEX IF EXISTS "saved_searches_userId_name_key";
DROP INDEX IF EXISTS "saved_searches_userId_idx";
DROP INDEX IF EXISTS "product_views_createdAt_idx";
DROP INDEX IF EXISTS "product_views_sessionId_idx";
DROP INDEX IF EXISTS "product_views_userId_idx";
DROP INDEX IF EXISTS "product_views_productId_idx";
DROP INDEX IF EXISTS "search_suggestions_searchCount_idx";
DROP INDEX IF EXISTS "search_suggestions_keyword_idx";
DROP INDEX IF EXISTS "search_suggestions_keyword_key";
DROP INDEX IF EXISTS "search_queries_createdAt_idx";
DROP INDEX IF EXISTS "search_queries_sessionId_idx";
DROP INDEX IF EXISTS "search_queries_userId_idx";
DROP INDEX IF EXISTS "search_queries_query_idx";
DROP INDEX IF EXISTS "product_recommendations_productId_recommendedProductId_type_key";
DROP INDEX IF EXISTS "product_recommendations_score_idx";
DROP INDEX IF EXISTS "product_recommendations_productId_type_idx";
DROP INDEX IF EXISTS "user_behaviors_createdAt_idx";
DROP INDEX IF EXISTS "user_behaviors_actionType_idx";
DROP INDEX IF EXISTS "user_behaviors_categoryId_idx";
DROP INDEX IF EXISTS "user_behaviors_productId_idx";
DROP INDEX IF EXISTS "user_behaviors_sessionId_idx";
DROP INDEX IF EXISTS "user_behaviors_userId_idx";
DROP INDEX IF EXISTS "bnpl_installments_paymentPlanId_installmentNumber_key";
DROP INDEX IF EXISTS "bnpl_installments_dueDate_idx";
DROP INDEX IF EXISTS "bnpl_installments_status_idx";
DROP INDEX IF EXISTS "bnpl_installments_paymentPlanId_idx";
DROP INDEX IF EXISTS "bnpl_installments_providerPaymentId_key";
DROP INDEX IF EXISTS "bnpl_payment_plans_status_idx";
DROP INDEX IF EXISTS "bnpl_payment_plans_provider_idx";
DROP INDEX IF EXISTS "bnpl_payment_plans_userId_idx";
DROP INDEX IF EXISTS "bnpl_payment_plans_orderId_idx";
DROP INDEX IF EXISTS "bnpl_payment_plans_providerPlanId_key";
DROP INDEX IF EXISTS "bnpl_payment_plans_orderId_key";
DROP INDEX IF EXISTS "subscription_invoices_stripeInvoiceId_idx";
DROP INDEX IF EXISTS "subscription_invoices_status_idx";
DROP INDEX IF EXISTS "subscription_invoices_subscriptionId_idx";
DROP INDEX IF EXISTS "subscription_invoices_stripeInvoiceId_key";
DROP INDEX IF EXISTS "subscriptions_stripeSubscriptionId_idx";
DROP INDEX IF EXISTS "subscriptions_status_idx";
DROP INDEX IF EXISTS "subscriptions_planId_idx";
DROP INDEX IF EXISTS "subscriptions_userId_idx";
DROP INDEX IF EXISTS "subscriptions_stripeSubscriptionId_key";
DROP INDEX IF EXISTS "subscription_plans_isActive_idx";
DROP INDEX IF EXISTS "subscription_plans_type_idx";
DROP INDEX IF EXISTS "ad_clicks_converted_idx";
DROP INDEX IF EXISTS "ad_clicks_timestamp_idx";
DROP INDEX IF EXISTS "ad_clicks_userId_idx";
DROP INDEX IF EXISTS "ad_clicks_adId_idx";
DROP INDEX IF EXISTS "ad_impressions_timestamp_idx";
DROP INDEX IF EXISTS "ad_impressions_userId_idx";
DROP INDEX IF EXISTS "ad_impressions_adId_idx";
DROP INDEX IF EXISTS "ad_keywords_adId_keyword_key";
DROP INDEX IF EXISTS "ad_keywords_keyword_idx";
DROP INDEX IF EXISTS "ad_keywords_adId_idx";
DROP INDEX IF EXISTS "advertisements_startDate_endDate_idx";
DROP INDEX IF EXISTS "advertisements_status_idx";
DROP INDEX IF EXISTS "advertisements_type_idx";
DROP INDEX IF EXISTS "advertisements_productId_idx";
DROP INDEX IF EXISTS "advertisements_vendorId_idx";
DROP INDEX IF EXISTS "advertisements_campaignId_idx";
DROP INDEX IF EXISTS "ad_campaigns_startDate_endDate_idx";
DROP INDEX IF EXISTS "ad_campaigns_status_idx";
DROP INDEX IF EXISTS "ad_campaigns_vendorId_idx";
DROP INDEX IF EXISTS "product_variants_sku_idx";
DROP INDEX IF EXISTS "product_variants_productId_idx";
DROP INDEX IF EXISTS "product_variants_sku_key";
DROP INDEX IF EXISTS "wishlist_userId_productId_key";
DROP INDEX IF EXISTS "wishlist_productId_idx";
DROP INDEX IF EXISTS "wishlist_userId_idx";
DROP INDEX IF EXISTS "review_votes_reviewId_userId_key";
DROP INDEX IF EXISTS "review_votes_reviewId_idx";
DROP INDEX IF EXISTS "reviews_status_idx";
DROP INDEX IF EXISTS "orders_trackingNumber_idx";

-- Remove columns from orders table
ALTER TABLE "orders" DROP COLUMN IF EXISTS "storeCreditAmount";
ALTER TABLE "orders" DROP COLUMN IF EXISTS "statusHistory";
ALTER TABLE "orders" DROP COLUMN IF EXISTS "shippingMethod";
ALTER TABLE "orders" DROP COLUMN IF EXISTS "notes";
ALTER TABLE "orders" DROP COLUMN IF EXISTS "giftCardAmount";
ALTER TABLE "orders" DROP COLUMN IF EXISTS "estimatedDeliveryDate";
ALTER TABLE "orders" DROP COLUMN IF EXISTS "carrier";
ALTER TABLE "orders" DROP COLUMN IF EXISTS "actualDeliveryDate";

-- Remove columns from reviews table
ALTER TABLE "reviews" DROP COLUMN IF EXISTS "status";
ALTER TABLE "reviews" DROP COLUMN IF EXISTS "isVerifiedPurchase";
ALTER TABLE "reviews" DROP COLUMN IF EXISTS "helpfulCount";

-- Drop tables (in reverse order of creation)
DROP TABLE IF EXISTS "_OrderGiftCards";
DROP TABLE IF EXISTS "store_credit_transactions";
DROP TABLE IF EXISTS "store_credits";
DROP TABLE IF EXISTS "gift_card_transactions";
DROP TABLE IF EXISTS "gift_cards";
DROP TABLE IF EXISTS "deal_analytics";
DROP TABLE IF EXISTS "deal_notifications";
DROP TABLE IF EXISTS "deal_purchases";
DROP TABLE IF EXISTS "deal_products";
DROP TABLE IF EXISTS "deals";
DROP TABLE IF EXISTS "referrals";
DROP TABLE IF EXISTS "reward_redemptions";
DROP TABLE IF EXISTS "rewards";
DROP TABLE IF EXISTS "loyalty_tier_benefits";
DROP TABLE IF EXISTS "point_transactions";
DROP TABLE IF EXISTS "customer_loyalty";
DROP TABLE IF EXISTS "loyalty_programs";
DROP TABLE IF EXISTS "translations";
DROP TABLE IF EXISTS "category_translations";
DROP TABLE IF EXISTS "product_translations";
DROP TABLE IF EXISTS "languages";
DROP TABLE IF EXISTS "traffic_analytics";
DROP TABLE IF EXISTS "revenue_analytics";
DROP TABLE IF EXISTS "category_analytics";
DROP TABLE IF EXISTS "product_analytics";
DROP TABLE IF EXISTS "vendor_analytics";
DROP TABLE IF EXISTS "saved_searches";
DROP TABLE IF EXISTS "product_views";
DROP TABLE IF EXISTS "search_suggestions";
DROP TABLE IF EXISTS "search_queries";
DROP TABLE IF EXISTS "product_recommendations";
DROP TABLE IF EXISTS "user_behaviors";
DROP TABLE IF EXISTS "bnpl_installments";
DROP TABLE IF EXISTS "bnpl_payment_plans";
DROP TABLE IF EXISTS "subscription_invoices";
DROP TABLE IF EXISTS "subscriptions";
DROP TABLE IF EXISTS "subscription_plans";
DROP TABLE IF EXISTS "ad_clicks";
DROP TABLE IF EXISTS "ad_impressions";
DROP TABLE IF EXISTS "ad_keywords";
DROP TABLE IF EXISTS "advertisements";
DROP TABLE IF EXISTS "ad_campaigns";
DROP TABLE IF EXISTS "product_variants";
DROP TABLE IF EXISTS "wishlist";
DROP TABLE IF EXISTS "review_votes";

-- Drop enums (in reverse order)
DROP TYPE IF EXISTS "TransactionType";
DROP TYPE IF EXISTS "StoreCreditType";
DROP TYPE IF EXISTS "GiftCardType";
DROP TYPE IF EXISTS "GiftCardStatus";
DROP TYPE IF EXISTS "DealStatus";
DROP TYPE IF EXISTS "DealType";
DROP TYPE IF EXISTS "ReferralStatus";
DROP TYPE IF EXISTS "RewardType";
DROP TYPE IF EXISTS "PointTransactionType";
DROP TYPE IF EXISTS "LoyaltyTier";
DROP TYPE IF EXISTS "AnalyticsPeriod";
DROP TYPE IF EXISTS "SearchSource";
DROP TYPE IF EXISTS "UserActionType";
DROP TYPE IF EXISTS "BnplInstallmentStatus";
DROP TYPE IF EXISTS "BnplPaymentPlanStatus";
DROP TYPE IF EXISTS "BnplProvider";
DROP TYPE IF EXISTS "BillingInterval";
DROP TYPE IF EXISTS "SubscriptionStatus";
DROP TYPE IF EXISTS "SubscriptionPlanType";
DROP TYPE IF EXISTS "AdStatus";
DROP TYPE IF EXISTS "AdType";
DROP TYPE IF EXISTS "CampaignStatus";
DROP TYPE IF EXISTS "ReviewStatus";
